### ISSUE TITLE
[Feature Request] Custom Craft Info Tooltip [ API, plugin ]  , Skillet [ API ] , [Plugins]  CraftSim , Journalator  , Text and Math Formating 

### ISSUE THREAD

**Issue by BodySame** [b-morgan/Skillet#100]
Hi. Creating items in the game has become popular. There are a couple of wishes for development.
    Maximum offer idea

1.1 Creating an API, DB.API or shared lib to obtain information or exchange between Skillet , CraftSim and other Addons.Skillet a very well made Craft UI, but with a minimum of statistics. Main problem - lack of text field customization  with fully enabled Auction DB plugins.Users need Way to edit or change text output and COLORIZE numbers

1.2 Create or add integration of selected information into tooltip, item tooltip, reagent tooltip.
With the ability to control position and color.

1.3 Custom Math( functions for output text strings from plugins).Creating simple calculated (arithmetic) variables (parameters, conditions) for using data from addonDB , Skillet Plugins As for CraftSim and Auction Addons DB , Auctionator, TSM, Journalator API (DB  maked Auctionator author with real sell data per character(user) , not just Auctionator DB).You can try seen an example of text coloring and condition code LibDogTag-3.0 a simple functional text formatting library.

    DogTag Supports Custom libs. Maked by IceHud UI addon autor.
    Example. Base Condition

```
 %AUCPrice / %SimPrice = %result(ColourRed,LineOne) 
If %AUCPrice / %SimPrice > 10 = %Result( ColourBlue,LineTwo) 
```

Example. DogTagLib Condition With Text And font Formating.

```
[Outline][White(Short(HP) Bracket(VeryShort(TotalAbsorb))) [if MinRange >= 40 then
   Color(MinRange "-" MaxRange,"19FCFF")
else
    Green(MinRange "-" MaxRange)
end]]
```

    Most acceptable offer idea
    Option 1.2 -1.3 Tooltip and simple functions or a window for displaying user-maked-calculated values.

Repost Curse Forge Comment.Some explanations.
 Custom Math( functions for output text strings from plugins) . CraftSim module  - calculated profit based on CraftSim  proffesion stats calculations.Or. Optional.  
Some Way to Use   Professions stats  and craft mats data (count items , cost(Auction,Vendor),count(reagent,tier,count,item stack))) to make custom user scripts(functions).
Example - just   simple interface to use or make  custom db values( operands) from all plugins, Example  for  auctionator plugin plugin data :  %AU  Profit%     TSM%    Mastery%  Mastery$ . 
Text field with math support (simple function) : %AU / %Profit = [Out]CustomData   to String in Item Recipe interface.

**Comment by b-morgan** [comment]
Neither CraftSim nor TradeSkillMaster have published (documented) and supported API interfaces. TSM in particular has been very uncooperative when dealing with Skillet related issues. The developers have an attitude that theirs is the only Professions addon. 

Other addons like Auctionator and Journalator do have published and supported APIs.

Skillet also has a documented plugin API. Plugins are provided that add cost and profit information with the Auctionator plugin being the most developed. These plugins were initially supplied by other people and I will accept additional plugins (or updates to existing plugins) if they provide generally useful features.

It sounds to me like you haven't used the Auctionator plugin. If you spend some time understanding the features provided by that plugin we can discuss any changes you think would be generally useful. There is some "colorization" provided.

Skillet provides two tooltip types. One is the tooltip for items in the recipe list (left side) and the other is for items in the detail (right) side. The detail item tooltips use the global GameTooltip and many addons add information to that tooltip.

Currently neither tooltip has provisions for adding additional information that, or instance, a user supplied plugin would provide. I would consider enhancing the current plugin API to provide access assuming we could agree on a reasonable specification.

Custom math functions and custom colorization are not something I wish to add to Skillet.

If you can provide some examples of where the current information that Skillet (and its plugins) provides needs to be enhanced we can discuss them.

**Comment by BodySame** [comment]
> If you can provide some examples of where the current information that Skillet (and its plugins) provides needs to be enhanced we can discuss them.

![2024-09-28_21-25-03](https://github.com/user-attachments/assets/7a388f6a-5b8a-4037-bbf6-89901a3dd379)

Text UI  with plugins DB info  use to many screen size % to text caption.
 UI Frame When Resize  Go over Screen Border

About  simple  math

Values cant be changed to %procent,Flat gold
Values cant be divided and calculate median
No way to calculate profit from craft T-T3 reagents

Skiller use "vacuum" profit sell-buy.
No based around craft stats or Craft simulation
Cant calculate One Reagents(count x gold) price  value % in  100%  of all craft  price value .

> Skillet provides two tooltip types

Notes Tooltip Not visible when option check  Notes tooltip on item tooltip
![2024-09-28_21-19-44](https://github.com/user-attachments/assets/6267f1a4-7b59-4050-be63-3c3e3029c496)

PS. Anyway Your Make great addon. I am  make plugin for stats  in future and  or with simple math. If you  not wish add not needed feature

**Comment by b-morgan** [comment]
I admit that Skillet doesn't mesh well with the Dragonflight (10.*) and The World Within (11.*) expansions. Considering the complexity of the new professions system, I doubt it will ever catch up with addons like CraftSim.

When the frame is resized off screen it can be corrected with a "/skillet reset" while the frame is displayed.

The bottom part of the recipe detail is generated by the plugins that are enabled. It sounds to me like you would like to replace one or more plugins with one(s) that compute and display the data you are interested in. My personal opinion is that it will take something on the order of CraftSim to get the right computations.

I think we need to separate problems with how the existing data / tooltips are displayed vs. the what data is or isn't displayed. I am happy to work with you to correct the display of existing data. When it comes to changing the data itself, I think you will need to do most of that work yourself. The existing plugins should give you a good template to start with.

**Comment by b-morgan** [comment]
With regards to "Notes". This feature has been around since before I took over the project. After playing with it some, I'm tempted to remove it completely. In any case, there are no tooltips involved.

**Comment by BodySame** [comment]
I am leave screenshot  what it ready (funct text field) (calculated values and functions) in Premade group finder https://github.com/0xbs/premade-groups-filter
<a href="https://ibb.co/F8dPRtk"><img src="https://i.ibb.co/F8dPRtk/2024-10-01-11-45-59.png" alt="2024-10-01-11-45-59" border="0"></a>

**Comment by b-morgan** [comment]
While you have had some useful input on problems with Skillet, I believe much of this issue is outside the scope of the project.

If you wish to pursue writing your own plugin to capture and display the data you believe is missing from Skillet, I'll consider including it with the Skillet distribution when it is ready.
