### ISSUE TITLE
Not Working Queue Crafting - Only One Craft

### ISSUE THREAD

**Issue by BodySame** [b-morgan/Skillet#101]
## Title: Skillet |cff7fff7f -Ace3-|r

Dump: value=GetLocale()
 [1]="ruRU"

Not Working Queue Crafting - Only One Craft per button click.
When Enabled Auctionator Plugin in options  and  Auctionator Addon disabled in Blizzard addon select UI . 

Queue Crafting Not Add Any items  Queue Crafting List.No Errors in BugSack

**Comment by b-morgan** [comment]
The War Within expansion has some changes to the crafting interface that are causing Skillet some grief atm. There is a Skillet option, "Queue one at a time" (sorry, the ruRU localization doesn't exist) which will allow crafting to limp along but it is not the ideal solution. I assume you have this option checked.

Use the latest alpha (or beta) which has (and will have) changes in this area as I figure them out.

I don't believe the Auctionator plugin has anything to do with this issue. Please provide examples if you disagree.

Skillet has extensive debugging output that can be enabled. We may need to capture some if I can't figure out what is causing the crafting issue on my own.

**Comment by BodySame** [comment]
>  "Queue one at a time". I assume you have this option checked.

May you help and post screenshot or link for screenshot where is this option

**Comment by b-morgan** [comment]
Click the "?" icon in the upper-right:

![image](https://github.com/user-attachments/assets/ffe92059-5a03-4a8b-81b5-06ca1010eacb)

Option is highlighted in red:

![image](https://github.com/user-attachments/assets/0c3d7df1-a226-4326-bfb9-7b501d9a0ae3)

**Comment by BodySame** [comment]
I checked several times - the add-on has problems with processing strings of various localizations and possibly with string encoding , may be fonts
the code of checks Data provided  plugin DBs causes errors that are not displayed anywhere.

**Must by Checked code**

input plugin DB 
output Skillet DB (UI string,numeric values)
Recipe Spell ID   = localized Item Name and Encoding
Reagent Count Materials

**Must by Checked code**

Fill Data Db  Skillet  after plugin enable in options
Empty Skillet Db if plugin unchecked in options.
Check  localized item name in Auctioneer or Other Tradeskill DB

**Must by Checked code**

Counting Free  Item slots in inventory. 
Full inventory in Blizzard UI Break ALL.In Bank to.

**Must be writed code**

Button to clear  all variables and shared db and options of addon.
I use curseforge client to clear all things .And some wat queue working


Constantly  message in log.

_Skillet: Insufficient (Required) Materials availa_

**Comment by b-morgan** [comment]
I am confining this issue to the problems with crafting (either with the craft buttons or the queue buttons follow by process.

The `Skillet: Insufficient (Required) Materials available` message is a known problem. The work around is to check the `Queue one at a time` option.

[Skillet-5.34-beta2](https://legacy.curseforge.com/wow/addons/skillet/files/5765106) may fix this problem (i.e. when the `Queue one at a time` option is NOT checked).

**Comment by b-morgan** [comment]
For the other localization issues:

Please provide examples / screenshots in one (or more) new issues. The localization of Skillet strings is done by volunteers using [https://legacy.curseforge.com/wow/addons/skillet/localization](https://legacy.curseforge.com/wow/addons/skillet/localization). 

I believe ruRU is about 86% complete

**Comment by b-morgan** [comment]
See issue #103 for the Auctionator issue.

**Comment by b-morgan** [comment]
More fixes in [Skillet-5.34-beta4](https://legacy.curseforge.com/wow/addons/skillet/files/5768664).

**Comment by b-morgan** [comment]
I am closing this issue because I believe the "Skillet: Insufficient (Required) Materials available" bug is fixed. Please open another issue if it is not and open separate issues for localization issues.
