### ISSUE TITLE
[Feature Request] Crafting for Disenchant, Prospeting , Mailing  (Profit , Cost , Stats)

### ISSUE THREAD

**Issue by BodySame** [b-morgan/Skillet#102]
Add Disenchant Radio Button in Queue - Crafting for Disenchant and Disenchant Queue . Cost , Profit. Queued Disenchant , Prospecting and other professions.

**Comment by b-morgan** [comment]
There is already a "Disenchant" button in the Skillet frame although I never use it. There are other addons that address this issue, [Breakables](https://www.curseforge.com/wow/addons/breakables) is the one I use. I don't understand how a queue for disenchanting would work.

Skillet has a documented plugin API. Plugins are provided that add cost and profit information with the Auctionator plugin being the most developed. These plugins were initially supplied by other people and I will accept additional plugins (or updates to existing plugins) if they provide generally useful features.

**Comment by BodySame** [comment]
I'll explain. A crafting queue has already been made in your add-on from basic components (reagents) to an item. It is necessary that after crafting the final item, it can be immediately disenchant. 
This is a **big** **difference** between a _queue_ of crafting in Skillet and just a disenchant few items without a queue crafting (crafting tree) for crafting items in [Breakables](https://www.curseforge.com/wow/addons/breakables)

Skillet has a Disenchant button, but does not have the functionality to Disenchant an item right after crafting.
It does not have simple functionality - use a macro or button from the command bar to do something with the received items.
The fact is that if you use the Breakables addon, the crafting queue will get lost because Disenchant without a queue is a higher priority than the crafting queue from Blizard TradeSkillUI
Here is the macro code that does this, but only when TradeSkillUI UI is open. If  closed,  then  working only for Enchanting Supplies

Example Macros Disenchant With Open UI :
May need Place Craft Recipe Spell on action bar first.

`/run  C_Spell.PickupSpell(376509)`

`/run C_TradeSkillUI.CraftRecipe(376509)`

Example Command Disenchant With Pickup Spell Drenor Disenchant without Open UI. 
Spell used from action bar.

`/run C_Spell.PickupSpell(224199)`


Example Macros With Open (loaded TradeSkillUI )

```
/cast Disenchant
/ use Item Name
```

**Comment by b-morgan** [comment]
I'll have to think about this one but off the top of my head, I don't think this is possible because of Blizzard's one action per hardware event. The CraftRecipe uses the hardware event so the Disenchant would require another hardware event.
