### ISSUE TITLE
Feature Request: Option to Set Default UI as Primary in Skillet

### ISSUE THREAD

**Issue by 168229** [b-morgan/Skillet#104]
Starting with version 10.0, Blizzard has revamped the profession UI. I used to never use the default UI, but I am now gradually accepting it and using it more frequently, especially for the Orders system. Of course, for more complex crafting processes, Skillet remains the best choice (e.g., Engineering's Wormhole Generator).

In the default Skillet settings, opening the default UI requires holding the Shift key and left-clicking. This worked very well and was very convenient in the past. However, with the increased usage of the default UI in the new version, I would like to ask if it would be possible to add an option (or setting) to allow players to configure which UI opens by default? For example, "left-click to open the default UI, Shift + left-click to open Skillet." Alternatively, is there a macro we could use to directly open the default UI?

Thank you very much!

**Comment by b-morgan** [comment]
Change line 1236 in Skillet.lua from `return true` to `return false` and use the CTRL key to open Skillet.

I'll add an option in the next release. It will be a chat command only, `/skillet swapshiftkey` which will toggle the behavior of the shift key.

I'll update this issue when I have a alpha release ready.

**Comment by b-morgan** [comment]
[Skillet-5.36-alpha1](https://legacy.curseforge.com/wow/addons/skillet/files/5971968) contains the `/skillet swapshiftkey` slash command. Note that `/skillet nomodkeys` (also a toggle) removes the effects of the shift, ctrl, and alt keys completely so this new slash command will have no effect.
