### ISSUE TITLE
Plugin help

### ISSUE THREAD

**Issue by makoshark2001** [b-morgan/Skillet#105]
version 2.05

In the plugins you have auctionaator. One of the check-boxes is for showing profit. Is there a way to make a checkbox to show profit to vendor only?  I want to craft the items that sell to vendors for more profit overall after cost of reagents from vendor.

**Comment by b-morgan** [comment]
I'm not sure this is what you want but replace `...\Skillet\Plugins\Auctionator.lua` with the one the attached zip file.

I added two new sorts, Sellout (the Vendor Sell Price) and VProfit (Vendor Sell Price - Cost). I did not add them to the list of Suffixes nor did I add these values to the detail data.

[Auctionator.zip](https://github.com/user-attachments/files/18201489/Auctionator.zip)

Note that the sort names are not localized so if your locale is not "enUS" then they may not display.

**Comment by makoshark2001** [comment]
I was looking for something like this since I want to make more money only selling to vendors no AH on HC
![Options](https://github.com/user-attachments/assets/77cb929b-4664-4bca-952a-ede0da78cdca)
![prices](https://github.com/user-attachments/assets/364cfaa9-a71e-469e-bb19-e7e6463c7653)

**Comment by b-morgan** [comment]
This is what I implemented:

![image](https://github.com/user-attachments/assets/f5056c46-0da4-4dc5-8bb7-5ac65a81389e)

Select Flat for the Grouping and ATR: VProfit for the Sort and you get a list of "Sell to Vendor for a Profit" recipes.

I believe the number of recipes that meet your criteria is small. Rather than search through each recipe looking at the details to find profitable items when sold to the vendor I just implemented a sort to show them to you.

If this isn't what you want, please show me why adding details is necessary.

**Comment by makoshark2001** [comment]
I set those and I get no values 
<img width="633" alt="Untitled" src="https://github.com/user-attachments/assets/4849d33c-0f7a-4fdc-b0fa-f79744e6e890" />

**Comment by b-morgan** [comment]
You posted this issue for Skillet (retail) so I tested on Skillet (retail). I'll have to test on Skillet-Classic and verify.

**Comment by makoshark2001** [comment]
My bad, didn't see a difference in versions here.

**Comment by b-morgan** [comment]
Here is a screen capture from Skillet-Classic on Classic Era (1.15.5):

![image](https://github.com/user-attachments/assets/30e13907-cd88-44b8-873c-5958bf33aea3)

**Comment by makoshark2001** [comment]
Here is what i have and all options. Maybe i am missing a setting or something?
<img width="1062" alt="1" src="https://github.com/user-attachments/assets/658fdd26-f44d-4a1f-9edd-855c7c7b8557" />
<img width="1164" alt="2" src="https://github.com/user-attachments/assets/2e7c5cd6-7633-4def-926e-435c7fe9d278" />
<img width="1163" alt="3" src="https://github.com/user-attachments/assets/4a7cb623-111d-4abd-a34d-6351c3313aa3" />
<img width="1201" alt="4" src="https://github.com/user-attachments/assets/af89e967-9cb7-493a-bdb4-194f4d0aab91" />

**Comment by b-morgan** [comment]
In Skillet, Plugins, Auctionator uncheck onlyPositive. This will show you the profit (or loss) for each recipe.

Since you have colorCode checked, I'm guessing all the recipes will have red values (i.e. there is nothing you can craft and sell to a vendor for a profit).

**Comment by makoshark2001** [comment]
Unchecked positive only and still no info,  maybe you have another addon that is providing that info?  or maybe i need to turn on a setting in auctionator?

**Comment by b-morgan** [comment]
Missed one... In the RecipeNameSuffix dropdown, select Auctionator.

**Comment by makoshark2001** [comment]
That fixed it.
