### ISSUE TITLE
Changing TradeSkill  Error

### ISSUE THREAD

**Issue by Galthariel** [b-morgan/Skillet#11]
<Please include the Skillet version number (from the title or the .toc file)>

Version **WAS** 4.25 (I just installed a 4.26-alpha1 and issue remains)

<Please include the output of "/dump GetLocale()" if it is different than enUS>

1x [ADDON_ACTION_FORBIDDEN] AddOn 'Skillet' tried to call the protected function 'CastSpellByName()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `CastSpellByName'
[string "@Skillet\Skillet-4.25.lua"]:1168: in function `ChangeTradeSkill'
[string "@Skillet\Skillet-4.25.lua"]:1220: in function `SetTradeSkill'
[string "@Skillet\UI\MainFrame.lua"]:626: in function `TradeButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

The error occurs when I'm with Skillet opened and at my **Leatherworking** Profession Frame. I then click the button to change it **Cooking** and NO ERRORS. But as soon I click again in the Leatherworking button I get the error above and also a small Blizzard window with **_"Skillet has been blocked from an action only available to the Blizzard UI. You can disable this addon and reload the UI._**

If I chose **Ignore**, Skillet closes and I can reopen it as usual although the issue happens again if I do the steps above.

**Comment by b-morgan** [comment]
Please see [https://github.com/b-morgan/Skillet/issues/1](url). If you logout and login again (without closing WoW.exe), this Blizzard bug won't bother you (until the next time).
