### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by susitucker** [b-morgan/Skillet#12]
Hello, would you consider adding a global profile option to this addon? All of my alts use the same profile, and having to change the alt profile to use the default is a little frustrating. I don't know how hard it would be to implement this feature, but I, for one, would love it. :) 

Regardless, thank you for maintaining this addon. It is a must-have for me!

**Comment by b-morgan** [comment]
I will confess that I am not one of the original authors of Skillet and the AceDB-3.0 stuff was in place long before I got involved in the project. If you know of an addon the uses AceDB-3.0 in the manner you describe, let me know which addon it is and I can look and see what they did differently than what Skillet does. I've looked at the AceDB-3.0 documentation and that doesn't give me any clues as to how to implement what you are asking for.

**Comment by susitucker** [comment]
I only have one other addon that uses a global profile, and that is SexyMap (I could have sworn there were others). I looked in the addons folder, and it has some Ace libraries, but I didn't see AceDB specifically, so I don't know if that will help you at all.

Thank you for the reply! I am totally fine with how it works now. Just thought I'd ask. :)

**Comment by b-morgan** [comment]
I've done some experimenting with the existing profile implementation and I believe it adequately addresses this request. A new alt will create a new, private profile. You can change that to a common profile used by all characters and this change is remembered across logins (i.e. from this point forward). Unless you are constantly creating alts, one change at the beginning of an alts life should not be frustrating.
