### ISSUE TITLE
error at auction house/banks

### ISSUE THREAD

**Issue by Fagerinfoco** [b-morgan/Skillet#13]
Skillet Version 4.26
Locale: enUS

my wife and I are getting errors when we mouse over things in the AH or the bank. it does not happen all the time. the error is below:

Message: Usage: GameTooltip:SetHyperlink(link)
Time: Sun Apr 18 09:44:34 2021
Count: 1
Stack: Usage: GameTooltip:SetHyperlink(link)
[string "@Interface\AddOns\Skillet\UI\ShoppingList.lua"]:168: in function `ShoppingListButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: self = <table> {
 DeleteIgnoreEntry = <function> defined @Interface\AddOns\Skillet\UI\IgnoreList.lua:159
 RecipeGroupPruneList = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:506
 SkillButton_NewGroup = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:2220
 guildText = 0
 ClearQueue = <function> defined @Interface\AddOns\Skillet\SkilletQueue.lua:223
 RecipeGroupInitFlatten = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:362
 RecipeGroupConstructDBString = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:482
 SkilletShow = <function> defined @Interface\AddOns\Skillet\Skillet.lua:962
 DisplayShoppingList = <function> defined @Interface\AddOns\Skillet\UI\ShoppingList.lua:1127
 ShowQueueView = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:3447
 ReagentStarsFrame_OnMouseEnter = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:3598
 SKILL_LINES_CHANGED = <function> defined @Interface\AddOns\Skillet\Skillet.lua:798
 SetSelectedTrade = <function> defined @Interface\AddOns\Skillet\Skillet.lua:1332
 FilterDropDown_OnShow = <function> defined @Interface\AddOns\Skillet\UI\Filtering.lua:25
 GARRISON_TRADESKILL_NPC_CLOSED = <function> defined @Interface\AddOns\Skillet\Skillet.lua:919
 hideTrivialRecipes = false
 SetTradeSkillLearned = <function> defined @Interface\AddOns\Skillet\SkilletData.lua:289
 guildbankQueryComplete = <function> defined @Interface\AddOns\Skillet\UI\ShoppingList.lua:459
 RecipeGroupSort = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:340
 EnableResize = <function> defined @Interface\AddOns\Skillet\UI\Utils.lua:72
 db = <table> {
 }
 bankBusy = false
 UpdateNotesWindow = <function> defined @Interface\AddOns\Skillet\UI\RecipeNotes.lua:116
 SetEnabledState = <function> defined @Interface\AddOns\Skillet\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 SkilletShowWindow = <function> defined @Interface\AddOns\Skillet\Skillet.lua:1026
 CHAT = <function> defined @Interface\AddOns\Skillet\DebugAids.lua:65
 HideOptionalList = <function> defined @Interface\AddOns\Skillet\UI\OptionalList.lua:226
 IgnoreList_OnScroll = <function> defined @Interface\AddOns\Skillet\UI\IgnoreList.lua:262
 SortDropdown_OnLoad = <function> defined @Interface\AddOns\Skillet\UI\Sorting.lua:488
 pluginsOptions = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\LibSharedMedia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RecipeGroupFlatten = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:378
 RecipeGroupMoveEntry = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:237
 FavoriteButton_OnClick = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:2299
 SkilletShowGuildCrafters = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:3167
 ITEM_DATA_LOAD_RESULT = <function> defined @Interface\AddOns\Skillet\Skillet.lua:923
 ShowReagentDetails = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:3149
 bopCheck = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:1607
 CHAT_MSG_SKILL = <function> defined @Interface\AddOns\Skillet\Skillet.lua:790
 SkillExpandButton_OnClick = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:2397
 TABLE = <function> defined @Interface\AddOns\Skillet\DebugAids.lua:313
 FixBugs = true
 Unhook = <function> defined @Interface\AddOns\Skillet\Libs\AceHook-3.0\AceHook-3.0.lua:418
 InventoryFilterButton_OnShow = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:2738
 SetTradeSkillToolTip = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:1515
 SetTradeSkill = <function> defined @Interface\AddOns\Skillet\Skillet.lua:

**Comment by b-morgan** [comment]
I cannot reproduce this error with the limited context supplied. Do you and your wife play on one machine or two? Is the shopping list open? What does the shopping list contain? Is the Skillet window open at the time?

The function `ShoppingListButton_OnEnter' should only be called when the shopping list is open, not empty, and you mouseover an item in the list. How it is being called when you mouseover items in the AH or the bank doesn't make sense to me.

**Comment by Fagerinfoco** [comment]
we play on separate machines. the shopping list opens when we click on the AH or when we open our banks. The shopping list contains the items needed in the various crafting queues. The skillet windows itself is not open, just the shopping lists. I do need to clarify something i noticed, the error ocurs when mousing over the shopping list, however, because it opens in basically the middle of the screen, it happens almost immediately when opening the bank or AH (as the shopping list opens with it)

**Comment by Fagerinfoco** [comment]
pulled the code and it appears to be working. thank you so much for the quick fix.
