### ISSUE TITLE
Engineering missing optional reagents choices

### ISSUE THREAD

**Issue by SaiBork** [b-morgan/Skillet#16]
Skillet 4.27

When looking at certain recipes it says there are 3 Optional Reagents, but it doesn't show all three settings. It does show all three in the Blizzard interface.

Level 60 Goggles:
Articulated Ectoplasmic Specs: This only shows a single "Specify a Secondary Stat"
Flexible Ectoplasmic Specs: This shows all three options
Grounded Ectoplasmic Specs: This shows "Specify a Secondary Stat" twice, but missing the Item Level option
Reinforced Ectoplasmic Specs: This shows all three options

**Comment by SaiBork** [comment]
Cleared WTF and all other addons, still the same, so nothing interfering. Also no lua errors to indicate an issue there.

**Comment by b-morgan** [comment]
Too many reagents not enough allocated! The details frame ran out of space. Unzip the following two files into `...\Interface\Addons\Skillet\UI\`

[UI.zip](https://github.com/b-morgan/Skillet/files/6526365/UI.zip)

You may have to resize the Skillet frame so that everything is visible.

**Comment by SaiBork** [comment]
Checked and can confirm all good. Everything fits without resize, but I can understand what you mean, especially with the Articulated Specs requiring a lot of reagents.
