### ISSUE TITLE
Shoppinglist command not working

### ISSUE THREAD

**Issue by SaiBork** [b-morgan/Skillet#17]
Skillet 4.27

I used this with previous versions to not have to open Skillet's interface and be able to only open the shopping list anywhere, but the command is not working.

/skillet shoppinglist command is not accepted when pressing enter

I type in /skillet shoppinglist in the chat window, but when I press enter it just stays there as if I'm not allowed to "say" it. No error comes up.
When I put a typo in, Skillet comes back with a message that the command is unknown.

It happens on all characters

If I have Skillet open and click the button it shows up without any issues.
I have it set to open shopping list at merchants and that works as well.

So the Shopping List itself works, but for some reason the command is being blocked?

**Comment by SaiBork** [comment]
Removed all addons and WTF folder, so clean wow setup. I now get the LUA error

Message: Interface\AddOns\Skillet\SkilletOptions.lua:517: attempt to call method 'IsShoppingListVisible' (a nil value)
Time: Sat May 22 10:12:09 2021
Count: 1
Stack: Interface\AddOns\Skillet\SkilletOptions.lua:517: attempt to call method 'IsShoppingListVisible' (a nil value)
[string "@Interface\AddOns\Skillet\SkilletOptions.lua"]:517: in function <Interface\AddOns\Skillet\SkilletOptions.lua:515>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Skillet\Libs\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua"]:143: in function <...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:133>
[string "@Interface\AddOns\Skillet\Libs\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua"]:408: in function <...\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:334>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Skillet\Libs\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua"]:769: in function `HandleCommand'
[string "@Interface\AddOns\Skillet\Libs\AceConfig-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua"]:781: in function `?'
[string "@Interface\FrameXML\ChatFrame.lua"]:5094: in function `ChatEdit_ParseText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4758: in function `ChatEdit_SendText'
[string "@Interface\FrameXML\ChatFrame.lua"]:4794: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: (*temporary) = nil
(*temporary) = <table> {
 DeleteIgnoreEntry = <function> defined @Interface\AddOns\Skillet\UI\IgnoreList.lua:159
 RecipeGroupPruneList = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:506
 SkillButton_NewGroup = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:2220
 guildText = 0
 ClearQueue = <function> defined @Interface\AddOns\Skillet\SkilletQueue.lua:223
 RecipeGroupInitFlatten = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:362
 RecipeGroupConstructDBString = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:482
 SkilletShow = <function> defined @Interface\AddOns\Skillet\Skillet.lua:967
 DisplayShoppingList = <function> defined @Interface\AddOns\Skillet\UI\ShoppingList.lua:1129
 ShowQueueView = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:3447
 ReagentStarsFrame_OnMouseEnter = <function> defined @Interface\AddOns\Skillet\UI\MainFrame.lua:3598
 SKILL_LINES_CHANGED = <function> defined @Interface\AddOns\Skillet\Skillet.lua:803
 SetSelectedTrade = <function> defined @Interface\AddOns\Skillet\Skillet.lua:1337
 FilterDropDown_OnShow = <function> defined @Interface\AddOns\Skillet\UI\Filtering.lua:25
 GARRISON_TRADESKILL_NPC_CLOSED = <function> defined @Interface\AddOns\Skillet\Skillet.lua:924
 hideTrivialRecipes = false
 SetTradeSkillLearned = <function> defined @Interface\AddOns\Skillet\SkilletData.lua:297
 guildbankQueryComplete = <function> defined @Interface\AddOns\Skillet\UI\ShoppingList.lua:461
 RecipeGroupSort = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:340
 EnableResize = <function> defined @Interface\AddOns\Skillet\UI\Utils.lua:72
 db = <table> {
 }
 bankBusy = false
 UpdateNotesWindow = <function> defined @Interface\AddOns\Skillet\UI\RecipeNotes.lua:116
 SetEnabledState = <function> defined @Interface\AddOns\Skillet\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 SkilletShowWindow = <function> defined @Interface\AddOns\Skillet\Skillet.lua:1031
 AdditionalButtonsList = <table> {
 }
 CHAT = <function> defined @Interface\AddOns\Skillet\DebugAids.lua:65
 HideOptionalList = <function> defined @Interface\AddOns\Skillet\UI\OptionalList.lua:226
 IgnoreList_OnScroll = <function> defined @Interface\AddOns\Skillet\UI\IgnoreList.lua:262
 SortDropdown_OnLoad = <function> defined @Interface\AddOns\Skillet\UI\Sorting.lua:488
 pluginsOptions = <table> {
 }
 UnregisterAllEvents = <function> defined @Interface\AddOns\Skillet\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RecipeGroupFlatten = <function> defined @Interface\AddOns\Skillet\RecipeGroups.lua:378
 RecipeGroupMove

**Comment by b-morgan** [comment]
That's what I get for moving an enhancement from Skillet-Classic to Skillet without testing it! Unzip the following file into `...\Interface\Addons\Skillet\UI\`

[ShoppingList.zip](https://github.com/b-morgan/Skillet/files/6526390/ShoppingList.zip)

The enhancement is that "/skillet shoppinglist" will open the frame if closed and close the frame if open.

The next build will include this fix if you prefer to wait.

**Comment by SaiBork** [comment]
Confirmed all working again, thanks for the quick fixes 😄
