### ISSUE TITLE
Messed up libs

### ISSUE THREAD

**Issue by Roktaal** [b-morgan/Skillet#2]
Message: Couldn't open Interface\AddOns\Skillet\Libs\AceAddon-3.0\AceAddon-3.0.xml
Time: Thu Feb 18 03:34:06 2021
Count: 3

and...

Message: Error loading Interface\AddOns\Skillet\Libs\LibWindow-1.1\LibWindow-1.1.lua
Time: Thu Feb 18 03:34:06 2021
Count: 3

Upon inspection of folder structure, detected that there is no AceAddon-3.0 folder

**Comment by freelycat** [comment]
same problem here as well

**Comment by Cudyhouse** [comment]
Just have to find some other addon with AceAddon-3.0\AceAddon-3.0.xml and copy/past into skillet for 1st lua error
For the second, just move LibWindow-1.1.lua from  Interface\AddOns\Skillet\Libs\LibWindow-1.1\LibWindow-1.1\LibWindow-1.1.lua ito the folder Interface\AddOns\Skillet\Libs\LibWindow-1.1\
and after a reload, all the error are gone.
at least the errors are gone for me after that folder replacement. (there is a mistake with double named folder for error 2)

**Comment by Excelis** [comment]
Same errors.  Read over Cudyhouse and figured out what he was saying.  Made those suggested changes but now I get:
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Skillet' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: ?
[string "=[C]"]: in function `CastSpellByName'
[string "@Skillet\Skillet-4.21.1.lua"]:1167: in function `ChangeTradeSkill'
[string "@Skillet\Skillet-4.21.1.lua"]:1219: in function `SetTradeSkill'
[string "@Skillet\UI\MainFrame.lua"]:626: in function `TradeButton_OnClick'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

**Comment by b-morgan** [comment]
Skillet-4.22 should fix this issue. The automated repository conversion from SVN to GIT missed some stuff.
