### ISSUE TITLE
For JS scraping wowhead

### ISSUE THREAD

**Issue by matthewhively** [b-morgan/Skillet#20]
What format of data do you want? Same as tbc-classic?
It should go into
```
local skillLevels = {
	[0] = "orange/yellow/green/gray"
}
```
right?

formatted as:
`[itemID] = "a/b/c/d",`
and
`[itemID] = { [spellID] = "a/b/c/d" },`

No segregation needed for "alchemy of outland" vs "alchemy of pandary" vs "shadowlands alchemy" right?

**Comment by b-morgan** [comment]
Yes, same format as tbc-classic. If the segregation is easy, then it can't hurt. If the segregation is hard, then it probably isn't necessary.

The separation by profession in Skillet-Classic was just comments so I imagine the segregation by expansion would just be comments as well.

**Comment by matthewhively** [comment]
Seems like it would be a pain segregate by expansion, so I'll just glob them all together by profession unless there is a code requirement that they be separated.

**Comment by b-morgan** [comment]
Retail SkillLevelData.lua has been copied from Classic and updated (the updates have been copied back to Classic). I should have a Skillet alpha build out later today.

**Comment by matthewhively** [comment]
Does archeology need skill level data?

**Comment by b-morgan** [comment]
No. Runeforging and Archeology are not supported by Skillet.

**Comment by matthewhively** [comment]
Looks like all recipes in retail only have 3 numbers: yellow/green/gray
Should I force it to have a 4th number as a copy of the yellow?

**Comment by matthewhively** [comment]
This may not work the way we want it to.
Apparently the live version of wowhead only rarely displays the orange level on the profession table view. It also displays an incorrect training level. If I click through into the actual spell page it will most likely display the orange level and the trainable level (which should be the same).
Obviously I've only tried a few examples because its very time consuming to check spells 1-by-1
see:
https://www.wowhead.com/alchemy#alchemy;100
look at the 5 earliest items at the bottom of the table.
the 3 starter items, have no orange listed even in the spell page.
Troll's blood and minor mana do list an orange level when on the spell page, but there is no way to view that from the table.

**Comment by matthewhively** [comment]
I submitted a feedback request asking wowhead to fix this... but I doubt they will.

**Comment by matthewhively** [comment]
I have some javascript that will read everything in the retail wowhead professions tables (or at least I squashed all the bugs I know of), but I don't have much reason to continue testing it unless we can accurately extract orange skill levels for most recipes :(

**Comment by b-morgan** [comment]
When a recipe is orange isn't really that important. What a user wants to know is when is it going to turn yellow, turn green, and turn gray. Can you tell when there is an orange value and when there isn't? If so, then when there isn't just set it to 1.

I rearranged and added debugs to the updated SkillLevelData.lua so that I could verify that TradeSkillInfo (I had to change the .toc) and LibPeriodicTable were getting results. They try both positive and negative itemID.

I probably should add a debugging option to gather all three sources and compare them (with debug output).

**Comment by b-morgan** [comment]
That probably works.

**Comment by matthewhively** [comment]
Hmmmm
What should be done for these?
https://www.wowhead.com/spell=310497/damage-retaliator

They seem work like enchantments, but are engineering.  Should they be negative?

**Comment by matthewhively** [comment]
Similar for these:
https://www.wowhead.com/spell=292320/blood-contract-bloodguard
https://www.wowhead.com/spell=124561/draconic-leg-reinforcements
https://www.wowhead.com/spell=279183/discreet-spellthread

**Comment by b-morgan** [comment]
My guess is that they are recipes that produce items so they should have a positive itemID (of the item produced).

I'm OK with 99+% correctness. There will be a few entries that are wrong and they can be fixed as needed if/when an issue is reported. The important thing is we will have the ability to make the fixes.

I don't understand how Wowhead processes the data that they collect. I just do my part in collecting it.

**Comment by matthewhively** [comment]
None of those items have an associated itemID, at least not that I can find.
I can just skip them if necessary, but what does skillet do for them currently?

**Comment by b-morgan** [comment]
Then skip them (adding a comment would be icing on the cake). 

I'll look and see if any of my toons know any of those recipes. Skillet will function without entries it just won't know when they change color (but it will know what color they are at the moment because that information does come from the Blizzard API).

**Comment by matthewhively** [comment]
@b-morgan New PR is up. I have done zero testing in retail client, so I hope it just works without additional tweaks.

**Comment by b-morgan** [comment]
Skillet-4.34-alpha2 contains this code.
