### ISSUE TITLE
Add slash-command to open Skillet UI directly

### ISSUE THREAD

**Issue by Alzarath** [b-morgan/Skillet#23]
**Situation:**
I would like to be able to access Skillet with a Shift+<character> keybind.

**Problem:**
Skillet innately overrides opening the Skillet UI with the Blizzard UI while holding Shift.

**Proposed Solution:**
Add a slash-command to open the Skillet UI directly that I could then macro.

**Alternate Solution:**
Add a config flag to disable this behavior.

**Comment by b-morgan** [comment]
Type `/skillet nomodkeys` and shift will no longer open the Blizzard UI.
