### ISSUE TITLE
Auto Queue

### ISSUE THREAD

**Issue by B1azeR5** [b-morgan/Skillet#25]
Good day.
I don't know if there is a setting somewhere, I didn't find it, but now, when you create a queue, you need to click "continue" every time you go to a new stage, is it possible to make a new stage start automatically without interrupting each time ?

**Comment by b-morgan** [comment]
Unfortunately Blizzard requires a "hardware event" for each spell cast. A "hardware event" is a key press or a mouse button press. The crafting spells have a count associated with them so a single spell can make multiples, but each line item in the queue is a new spell requiring another "hardware event".
