### ISSUE TITLE
skillet and guildbook

### ISSUE THREAD

**Issue by stpain** [b-morgan/Skillet#26]
![image](https://user-images.githubusercontent.com/47498931/133256004-78215ade-84d5-403a-9534-f49856ca11f0.png)

Hi so i've had this bug reported, have you noticed any issues when using guildbook?

Does skillet hide the default blizzard ui?

Regards

Sam

**Comment by b-morgan** [comment]
Since Guildbook is a Classic Era, Burning Crusade Classic only addon, the original poster must be using Skillet-Classic. This issue should be posted [there](https://github.com/b-morgan/Skillet-Classic). I have opened https://github.com/b-morgan/Skillet-Classic/issues/48.
