### ISSUE TITLE
Profession World Quests Stays in Queue After Crafting the Item and Completing the Quest

### ISSUE THREAD

**Issue by Galthariel** [b-morgan/Skillet#28]
Version I'm using is
Skillet-4.35

Intermittent issue similar to the previous one you've fixed a couple weeks ago. Remember when Legendaries stays in queue after crafting them? That one is 100% fixed but it happens sometimes with the Professions quests (Cooking, Leatherworking, Jewelcrafting and Engineering. Like I said doesn't happens ALL the time. It's intermittent. Sometimes happens and sometimes don't :-)

**Comment by b-morgan** [comment]
I've seen this occasionally on Burning Crusade Classic / Skillet-Classic. If you turn on Skillet debugging ("/skillet debugshow on", "/skillet debugshow off", which leaves the logging to the character specific saved variables file turned on), then when it happens, zip and attach the saved variables file.

I'll do some research and see if I need more debugging statements to capture what is going on and let you know.

**Comment by Galthariel** [comment]
Will do as soon I see a profession WQ. Will keep you posted :-)

**Comment by b-morgan** [comment]
Apparently there has not been a reoccurrence of this issue in quite a while. Please open a new issue if new details emerge.
