### ISSUE TITLE
9.1.5 Bug with SetBackdropBorderColor()

### ISSUE THREAD

**Issue by lotsoftoons** [b-morgan/Skillet#34]
## Version: 4.36

13x [string "SkilletSkillTooltip:OnLoad"]:1: attempt to call method 'SetBackdropBorderColor' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>

Locals:
self = SkilletSkillTooltip {
 0 = <userdata>
 NineSlice = <unnamed> {
 }
 textRight2Font = "GameTooltipText"
 TextRight2 = SkilletSkillTooltipTextRight2 {
 }
 layoutType = "TooltipDefaultLayout"
 textLeft1Font = "GameTooltipHeaderText"
 TopOverlay = <unnamed> {
 }
 TextLeft2 = SkilletSkillTooltipTextLeft2 {
 }
 TextRight1 = SkilletSkillTooltipTextRight1 {
 }
 BottomOverlay = <unnamed> {
 }
 TextLeft1 = SkilletSkillTooltipTextLeft1 {
 }
 textLeft2Font = "GameTooltipText"
 textRight1Font = "GameTooltipHeaderText"
}
(*temporary) = nil
(*temporary) = SkilletSkillTooltip {
 0 = <userdata>
 NineSlice = <unnamed> {
 }
 textRight2Font = "GameTooltipText"
 TextRight2 = SkilletSkillTooltipTextRight2 {
 }
 layoutType = "TooltipDefaultLayout"
 textLeft1Font = "GameTooltipHeaderText"
 TopOverlay = <unnamed> {
 }
 TextLeft2 = SkilletSkillTooltipTextLeft2 {
 }
 TextRight1 = SkilletSkillTooltipTextRight1 {
 }
 BottomOverlay = <unnamed> {
 }
 TextLeft1 = SkilletSkillTooltipTextLeft1 {
 }
 textLeft2Font = "GameTooltipText"
 textRight1Font = "GameTooltipHeaderText"
}
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = "attempt to call method 'SetBackdropBorderColor' (a nil value)"

**Comment by b-morgan** [comment]
Fixed in Skillet-4.37
