### ISSUE TITLE
Feature request: glyph sorting in inscription profession

### ISSUE THREAD

**Issue by ncplus0** [b-morgan/Skillet#38]
HI

is there a way you can include a filter just for glyphs and able to sorting by class as well.
the search option does nop find the class we want to find

tks

**Comment by ncplus0** [comment]
yes thats exactly what i need, exacly like that image

**Comment by ncplus0** [comment]
for me it does not work
if i search only glyph it gives all the glyphs
![image](https://user-images.githubusercontent.com/72767232/140960336-77593b22-ff51-4ecf-81ea-74f8758bbcd2.png)

but if a write glyph hunter i get nothing, no matter the class
![image](https://user-images.githubusercontent.com/72767232/140960569-d09e195c-4f73-4d90-b620-5a394a75c03d.png)

but if i select filter unlearn it appears a glyph that i don't kwon
![image](https://user-images.githubusercontent.com/72767232/140960822-4cd69d32-2e4e-460d-83cc-93680b02b3d0.png)

**Comment by ncplus0** [comment]
i've discoved the probtlem its the addon mogpartialsets that blocks the data
https://www.curseforge.com/wow/addons/mogpartialsets

btw.

**Comment by b-morgan** [comment]
Creating custom groups can be tricky. I didn't write that code and I stay as far away from it as I can. New Group, Empty Group doesn't work for me either so here's a step-by-step to get you started. 

1. Using the arrow next to Grouping, click New
2. Using the arrow next to Grouping, click Rename
3. Type the new name in the dropdown
4. Switch back to Blizzard group
5. Type "glyph hunter" in the search box
6. Click any of the results and type ctrl-A
6. Right-click and select Copy (ctrl-C also works)
7. Click the clear icon next to Search textbox
8. Select your new group from the Grouping dropdown
9. Right-click in the results area and click paste (ctrl-V also works)
10. Click any of the results and type ctrl-A.
11. Right-click and select New Group, From selection.
12. Right-click on the group name and click Rename

Repeat steps 4-12 only in step 10, click the first new recipe, shift-click the last new recipe, and then do steps 11-12.

It gets easier as you play with it. I took 5 random recipes from the Blizzard group and then just played with the right-click menus until I found something that worked for me.

Let me know if you continue to have problems getting it to work. Give me a step-by-step for a failure so I can reproduce it.
I think there are still bugs in the this part of the code but I get confused just looking at it so I need something specific to focus on.

**Comment by ncplus0** [comment]
tks im doing that, 
btw: can you create this groups in a future patch so that all have this group already created

**Comment by b-morgan** [comment]
>can you create this groups in a future patch so that all have this group already created

No because it is based on recipes known by each character.

**Comment by bcoca** [comment]
note: you can also paste 'unlearned' eyepieces, but the group display does not interact normally with the 'learned/unlearned' filter. It always displays 'all'  when you filter by 'learned', when you filter by 'unlearned' it highlights (in orange) the unlearned ones.
