### ISSUE TITLE
Feature Request Filter

### ISSUE THREAD

**Issue by Galthariel** [b-morgan/Skillet#39]
Hello Morgan and Happy New Year :-)

I was wondering if is hard to implement a simple Filter option between Leather and Mail (LW in this case). I know I can filter Leather Armor but by Expansion but not filter Leather Armor for ALL the expansions at the same time. Unless I'm not seeing it or missing something :-)

Thanks in advance,

Galth

**Comment by b-morgan** [comment]
The filtering options offered by Skillet are those provided by Blizzard so there's not an opportunity to enhance them.

You should, however, be able to use custom groups to accomplish this. Create two custom groups, Leather and Mail and then copy and paste the Blizzard groups from each expansion into these groups.

![Leather](https://user-images.githubusercontent.com/1547854/148417696-b5231e2a-a5a7-4696-8774-5d0a77cc908d.jpg)

I was able to copy the first group by right-clicking on the header. For the next groups, I had to click the first recipe in the group, shift-click the last recipe in the group, copy, paste in the custom group, and then while selected right-click and use new group from selection. You can then right-click each header and rename it. I didn't write this code and I struggle to maintain it but I can usually find a way to make it work.

**Comment by Galthariel** [comment]
That made the trick. Tks :-)
