### ISSUE TITLE
Not an Issue but a Request for Help

### ISSUE THREAD

**Issue by Galthariel** [b-morgan/Skillet#40]
Hello Morgan :-)

Quick help please. I'm trying to use a macro like this with Skillet and I was wondering what should I use for the frame line since this one is for the Blizz  frame. In case it's possible of course :-)

/script TradeSkillFrame.DetailsFrame:Create();
/use Enchanting Vellum

**Comment by b-morgan** [comment]
What are you trying to accomplish?

**Comment by Galthariel** [comment]
I got this from a Profession guide

Enchanting macro

Type /m into your chat then hit enter to create a macro. Then just copy-paste these strings in your macro and bind it to a useful/easy button on your keyboard. Simple but useful macro to make enchants faster.

/script TradeSkillFrame.DetailsFrame:Create();
/use Enchanting Vellum

This macro basically clicks on the "Enchant" button in your spellbook, then puts the enchant on an Enchanting Vellum. You have to select the Enchants in your profession spell book first, or the macro won't work.

**Comment by b-morgan** [comment]
How about alt-click or right-click on the Create button to put the selected enchant on a vellum? You should be able to queue enchants, use the shopping list etc. to obtain the necessary materials, and then alt-click or right-click on the Process button.

I think you can do more than one at a time using this method as well.

**Comment by Galthariel** [comment]
Ok. Tks :-)
