### ISSUE TITLE
Problem With Queuing Eternal Cauldrons

### ISSUE THREAD

**Issue by lotsoftoons** [b-morgan/Skillet#41]
<Please include the Skillet version number (from the title or the .toc file)>
<Please include the output of "/dump GetLocale()" if it is different than enUS>

## Interface: 90200

When I queue up Eternal Cauldrons, Skillet thinks that they only require 5 Spectral Flasks of Power, instead of 8.

**Comment by b-morgan** [comment]
Skillet just asks Blizzard's API, which sometimes lies (esp. right after logging in). My guess is if you close Skillet and open it again it will have the right count.

You say "when I queue". Does it show the correct count on the detail side of the frame?

I don't have an max level alchemist so I may need you to enable debugging if the above doesn't work.

**Comment by b-morgan** [comment]
Closing due to no additional input.
