### ISSUE TITLE
Feature Request - Profit Column

### ISSUE THREAD

**Issue by Goss444** [b-morgan/Skillet#43]
In the crafting windows would it be possible to add a profit column?

**Comment by b-morgan** [comment]
Note: The AH cost of materials (and the cost of finished goods) rely on the AH addons ability to collect this data. For Auctionator (and Auctioneer), this information is collected by scanning the AH. Skillet also relies on other addons and/or merchant scans to determine if items are buyable or not. In the example shown above, I believe Penumbra Thread is a buyable item, but my character has not visited a merchant that sells it and someone is scalping in the AH.
