### ISSUE TITLE
Skillet icon bug

### ISSUE THREAD

**Issue by Raismoter** [b-morgan/Skillet#44]
<Please include the Skillet version number (from the title or the .toc file)>
<Please include the output of "/dump GetLocale()" if it is different than enUS>
skillet v 4.40
"itIT"

Hello my friends i would like to show you a bug about icon in skillet
in few word like you can check from icon if you open the mini windows about the optional reagent each time you open for example a windows with 4 reagent and reopen a windows with more than 4 all the other icon will disappear if open a windows with 2 all the other upper the 2 second icon will disappear in anyother optional reagent
i hope my explain is clear however the image should be easy to understand

thanks for your patience and for your time ^^

![WoWScrnShot_060622_124248](https://user-images.githubusercontent.com/41512823/172147787-4ffe17d2-79d4-4601-840e-018ef8539f5c.jpg)
![WoWScrnShot_060622_124303](https://user-images.githubusercontent.com/41512823/172147795-efd3d390-5fe9-4462-b1fc-355d1d82583d.jpg)
![WoWScrnShot_060622_124307](https://user-images.githubusercontent.com/41512823/172147800-9952b5b2-047b-43f2-a52a-5285e13dccab.jpg)
![WoWScrnShot_060622_124316](https://user-images.githubusercontent.com/41512823/172147803-916d40e6-4211-4914-aac9-ec9b459db14e.jpg)
![WoWScrnShot_060622_124335](https://user-images.githubusercontent.com/41512823/172147806-f2f80e7f-0691-4308-ad58-ee210fe85d0b.jpg)
![WoWScrnShot_060622_124339](https://user-images.githubusercontent.com/41512823/172147812-a4af4467-fb07-44a7-8c51-3b3b2c03f6ee.jpg)

**Comment by b-morgan** [comment]
This will be fixed in the next release. The patch below to `...\Addons\Skillet\UI\OptionalList.lua` will fix your version.
```
@@ -190,6 +190,7 @@
 			needed:SetText("")
 			texture = GetItemIcon(oreagentID)
 			icon:SetNormalTexture(texture)
+			icon:Show()
 			button:SetID(itemIndex)
 			button:Show()
 		else
```

**Comment by Raismoter** [comment]
thanks for your help but i don t understand where have to add the the patch

looking for all the line i find this command  
text:SetText("")
			icon:Hide()
			count:SetText("")
			needed:SetText("")
			button:SetID(itemIndex * 100)
			button:Hide()
		end
	end
end

i should add the patch here upper this line ??
i already try at the beginning ang just up this command but doesen t work

where i have correctly add the patch ??

thanks again for your help ^^

**Comment by b-morgan** [comment]
Download [Skillet-4.41-alpha2](https://www.curseforge.com/wow/addons/skillet/files/3820082).
