### ISSUE TITLE
[Request] Keybinds

### ISSUE THREAD

**Issue by DreamsUnderStars** [b-morgan/Skillet#45]
Could you add in a keybind to open the crafting window? I feel like this used to be a thing, but maybe I always just put a crafting icon on the hotbar...

**Comment by b-morgan** [comment]
To the best of my recollection, Skillet has never had keybindings. Skillet is "opened" by responding to the events triggered by using the spells Blizzard provides for opening professions. Any keybinds would be of those spells so I don't see anything for Skillet to do.
