### ISSUE TITLE
Sometimes will not list my recipes

### ISSUE THREAD

**Issue by megamanzteam** [b-morgan/Skillet#46]
<Please include the Skillet version number (from the title or the .toc file)>
4.41
<Please include the output of "/dump GetLocale()" if it is different than enUS>
1 enUS

I have one character in particular that I can see the various blizzard groupings but under them there is no lists.

See Screenshot: 
![error](https://user-images.githubusercontent.com/4212359/185541024-aff7b40f-0c01-4db1-9871-2bff20d6c219.png)

For this character it doesn't seem to matter if I quit and login or doing a ui reload. Please let me know what else you need to help troubleshoot this.

**Comment by b-morgan** [comment]
I see from your screenshot that you are filtering out all but recipes that are Orange. Change that to Grey and everything should show up again. Let me know if that fixes the issue.

**Comment by megamanzteam** [comment]
OK I am blind. That was the issue, just don't recall turning on the filter. Thanks for the help!
