### ISSUE TITLE
Retail bug while in Auchenai TBC.

### ISSUE THREAD

**Issue by Wizardling** [b-morgan/Skillet#47]
8x Skillet\Skillet-4.41.lua:1310: Usage: CastSpellByName(name[, target])
[string "=[C]"]: in function `CastSpellByName'
[string "@Skillet\Skillet-4.41.lua"]:1310: in function `ChangeTradeSkill'
[string "@Skillet\SkilletQueue.lua"]:362: in function `ProcessQueue'
[string "@Skillet\SkilletQueue.lua"]:476: in function `CreateItems'
[string "*:OnClick"]:2: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = nil

**Comment by b-morgan** [comment]
I need more context. What is the significance of being "in Auchenai TBC"? What were you crafting? What (if anything) did Skillet output in chat? Can you provide a screenshot at the time of the failure? Please upload your global saved variables file Skillet.lua.

**Comment by Wizardling** [comment]
As I recall I was not crafting anything. Just mining the odd ore node.

**Comment by b-morgan** [comment]
Did you have anything in the Skillet queue for this toon? For any other toons? I have no idea how to begin debugging this issue. I would need a reproducible case preferably by me but if you can reliably reproduce it I could work with that.

The traceback indicates that one of the Create buttons in the Skillet frame was clicked. If the Skillet frame wasn't open, then I have no idea how that code got called. Perhaps a delete and reinstall of Skillet is in order just to rule out any corrupted files.

**Comment by Wizardling** [comment]
I'll wait and see if it happens again, then do a better job of taking note of what's going on. Another addon - https://www.curseforge.com/wow/addons/advanced-scrolling-combat-text/ - was bugging out badly at the time (every single time combat happened), after an update to it that clearly wasn't tested. Plus this Skillet bug has only occurred once. So wait and see seems the best path right now :-)

[Skillet.zip](https://github.com/b-morgan/Skillet/files/9463475/Skillet.zip)

**Comment by b-morgan** [comment]
I don't believe that there is anything in Skillet that needs to change. Please reopen this issue if it happens again.
