### ISSUE TITLE
Question: Dragonflight?

### ISSUE THREAD

**Issue by Earthling-Z3R0** [b-morgan/Skillet#51]
Hey there! I was wondering whether you are planning to make Skillet work in WoW Dragonflight since the whole crafting UI has been subject to a lot of changes!?

**Comment by b-morgan** [comment]
I have looked at it and you are correct, the crafting UI is completely new and there is no documentation on the new API. So far, I can't even get a frame to load.

It will most certainly not be available at launch and there is a possibility that it will never be available.

**Comment by BigFire321** [comment]
ACE3, which this mod heavily use is currently not compatible with pre-patch.

**Comment by b-morgan** [comment]
Yes. There are numerous compatibility issues right now. I'm waiting for much of this to settle out.

**Comment by b-morgan** [comment]
Skillet-5.00-alpha2 should load without error and display something resembling your current recipes. Lots of stuff is untested and lots of stuff is probably broken. If you are brave enough to try it, please open separate issues for each problem found so I can keep track of what works and what doesn't.
