### ISSUE TITLE
Skill leveling bar

### ISSUE THREAD

**Issue by DreamsUnderStars** [b-morgan/Skillet#52]
https://imgur.com/lOHZ09Z

The level bar at the top, or whatever it's called shows x/75 for classic, instead of 300.

**Comment by b-morgan** [comment]
his is because `C_TradeSkillUI.GetBaseProfessionInfo()` lies to me. Obviously, there must be some other way to get the 300 value but I'll have to figure out where.

```
ScanTrade: GetBaseProfessionInfo()= { ['skillLevel'] = 147, ['professionID'] = 185, ['skillModifier'] = 0, ['profession'] = 5, ['isPrimaryProfession'] = false, ['professionName'] = Cooking, ['maxSkillLevel'] = 225, ['expansionName'] = Unknown }"
```

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha4](https://www.curseforge.com/wow/addons/skillet/files/4073408) changes the way I determine the maxSkillRank. If this doesn't fix your character, please open your profession and execute the following:
`/dump C_TradeSkillUI.GetChildProfessionInfos()`

My level 10 toon went to the cooking trainer and learned "Cataclysm Cooking" which has a maxSkillRank of 75 so his bar is "messed up" in a different way!
