### ISSUE TITLE
Version: 5.00-alpha4:  unable to process enchant

### ISSUE THREAD

**Issue by Wyveryx** [b-morgan/Skillet#53]
Everything loads with no errors presented, however, when I go to process an enchant (one that I know that I have mats for) I get an error printed into chat.

"Skillet: Insufficient Materials available, count= 1, numAvailable= 0"

I've provide a screenshot.

Edited because apparently the link to imgur was being rerouted back to GitHub...

https://imgur.com/Meo3d3M

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha5](https://www.curseforge.com/wow/addons/skillet/files/4073990) should fix this issue.

FYI, you can drag and drop images into issues on GitHub.

**Comment by Wyveryx** [comment]
Thank you, 

It has fixed the issue, and I'll remember the drag and drop for any future use as well :
