### ISSUE TITLE
Can't craft more than one at a time

### ISSUE THREAD

**Issue by LasombraK** [b-morgan/Skillet#54]
<Please include the Skillet version number (from the title or the .toc file)>
alpha-5
<Please include the output of "/dump GetLocale()" if it is different than enUS>
zhCN

I tried jewel and enchant, it couldn't process items one by one by itself, such as I want to make 10 gems, like  [Quick Jewel Cluster].
It only could make one of them, and then it stopped. If I put the process button, there will show "Skillet: Cancle incomplete processing" in the chat frame, and put the button again, nothing happened.
One more thing, the "Prospecting ore" button is not working.
![skillet](https://user-images.githubusercontent.com/31497461/200588798-66516f86-5195-44f8-8a02-e5d1bebc1bf2.jpg)

Poor English, forgive me!

**Comment by b-morgan** [comment]
I have moved "One more thing..." to its own issue.

**Comment by b-morgan** [comment]
Neither Skillet nor TradeSkillMaster (in TSM4 mode) will craft more than one item at a time. I believe this is either a Blizzard bug or a new Blizzard feature designed to torpedo crafting addons.

**Comment by grimmtooth** [comment]
Since the default UI does not see issues with this my uneducated guess at this point is that they changed the API in some mysterious, possibly undocumented way. Business as usual with WoW Lua APIs. I don't even know who to ask TBH.

The LUA API peeps should take a lesson from the REST API peeps.

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha11](https://www.curseforge.com/wow/addons/skillet/files/4082952) has a hack that appears to solve this issue. Let me know if it works for you.

**Comment by grimmtooth** [comment]
Looks to be working okay for Inscription. Tested with mass milling and ink making.  Hack or not, it looks good here.
