### ISSUE TITLE
Vendor auto purchase not working at ink trader

### ISSUE THREAD

**Issue by grimmtooth** [b-morgan/Skillet#57]
Version 5.00-alpha5
English locale

In the past, I could create a bunch of Umbral Ink, queue glyphs, and then open a vendor window with the ink trader in Oribos and have the option to buy matts automatically. That is not working now.

Let me know if there's anything I can grab for you.

E2A: this button DOES appear for pigments. I.e. I had a bunch of pigments set up, queued inks up for each, and when I opened the vendor window there was a mats button that worked.  So this appears to only be broken for the ink vendor?

E2A2: Oh, I notice that the queue looks like this now (see the "+0 at the end, that's odd)

![image](https://user-images.githubusercontent.com/16244433/200709826-7af308fb-b2fd-4604-ad98-30081137a542.png)

E2A3: when I bring up the shopping list it shows the correct quantities.

**Comment by b-morgan** [comment]
I'll do the easy part first! The "+0" says there are no optional reagents for this queue entry. In Shadowlands, no optional reagents was represented by the absence of the key, in Dragonflight, it is represented as a key with the value 0. The "+0". The next alpha will remove the "+0".

For the hard part... I thought it was a new topink (i.e. the ink used as the currency) but I think I'm wrong. Unfortunately, my Inscriptionist knows Shadowlands Inscription (at skill 1), but he is only level 49 and has no Umbral Ink to trade. It would take me a while to level him up so he could survive and to make matters worse, he is an Inscriptionist and an Enchanter so I would have to level my Herbalist who is only 47!

However, there may be some good news... I believe the itemID I have for Umbral Ink is wrong. Please change line 872 in `Addons\Skillet\SkilletTables.lua` to:

`local topink = 173058				-- Umbral Ink`

and let me know if that fixes it. At some point, Blizzard is going to change the currency used by the Ink Trader and you will probably know before I do. Please open a new issue when that happens and I can fix this table.

**Comment by grimmtooth** [comment]
Thanks, Brad. I'll give this a shot this evening when I get home. Will update you on the results.

Yeah, they'll probably change the ink for DF proper, but they're not very communative on this so we'll see. We can at least test this iteration before then. :)

**Comment by b-morgan** [comment]
With a little help from the Auction House, I was able to verify the Umbral Ink itemID change.

[Skillet-5.00-alpha6](https://www.curseforge.com/wow/addons/skillet/files/4075520) contains this fix, the "+0" fix, and a fix for the Merchant interaction. I'm not sure how you got any merchants  to work at all but this version contains a fix for that as well.

You are still on the hook for monitoring the Ink Trader!

**Comment by grimmtooth** [comment]
Brad,

alpha7 worked well. I think you can close this ticket.

And of course I'll be your Inscription test dummy :)  

Feel free to poke me.
