### ISSUE TITLE
ShoppingList fails when opening bank

### ISSUE THREAD

**Issue by GeoRam2016** [b-morgan/Skillet#59]
4x Interface/AddOns/Skillet/UI/ShoppingList.lua:318: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Interface/AddOns/Skillet/UI/ShoppingList.lua"]:318: in function <Interface/AddOns/Skillet/UI/ShoppingList.lua:304>
[string "@Interface/AddOns/Skillet/UI/ShoppingList.lua"]:417: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha16](https://www.curseforge.com/wow/addons/skillet/files/4097879) is a better fix (i.e. doesn't break something else)
