### ISSUE TITLE
Auctionator price info now showing

### ISSUE THREAD

**Issue by DonSerrot** [b-morgan/Skillet#6]
The last working version I found was 4.20 where the Auctionator pricing info showed. I actually literally just put the 4.20 version of Auctionator.lua from the Plugins folder into the 4.24 Plugins folder and it works again. Not sure what changed and I don't have a good way to compare the code myself (or an understanding of lua to begin with) to pinpoint where the problem is other than with the Auctionator plugin itself. So far I haven't seen any errors with the old plugin, but it's only been a few minutes of trying it on a whim.

**Comment by b-morgan** [comment]
The Auctionator plugin in 4.24 is working for me. The 4.24 version has some new features which are controlled by some new options so you might want to check your options (or compare options with the 4.20 version with the 4.24 version).

**Comment by DonSerrot** [comment]
That was the problem. I had showPropitValue turned off for some reason.

**Comment by b-morgan** [comment]
You didn't have showProfitValue turned off because that was a new option added after 4.20 :smile:
Perhaps the default value of that option should be true for upwards compatibility.

**Comment by DonSerrot** [comment]
Having it default to on would certainly help prevent confusion. 😉

**Comment by b-morgan** [comment]
Next release will have an option something like "Always show headers with progress bars" and the default for showProfitValue will be true. Maybe I'll even get the Mining "bug" fixed.
