### ISSUE TITLE
Profession tools

### ISSUE THREAD

**Issue by Addonman** [b-morgan/Skillet#60]
alpha 15
Did i notice wrong,but i cant see them anywhere?

**Comment by b-morgan** [comment]
I think I'm going to need a screenshot (you can drag and drop it here). I reworked the required tools in alpha14 because they were missing and they appear to be working on my system with alpha15.
![image](https://user-images.githubusercontent.com/1547854/202797285-a1ef3f44-077b-467a-90f4-b87f4fe236f3.png)

**Comment by Addonman** [comment]
I even wasnt thinking about making them since i wasnt sure if they are in game already.But when i looged in(havent played since 10.o patch) i got notifications for stuff like fishing pol or enchanting rod. You can place them with right click and get blizz ui for profession (broken ofc) ,but i cant see in your ui where to put them. Those 3 boxes for them .Thats what i was asking? Hopefully i made it more clear now.

**Comment by b-morgan** [comment]
I think I'm more confused now than I was before. Skillet is a replacement for Blizzard's Profession UI. With patches 10.0.0 and 10.0.2 (Dragonflight), Blizzard has completely rewritten the UI. Skillet, on the other hand, looks very much like it did in 9.*.* (Shadowlands).

What level is your character and what professions does your character have? 

Skillet does not support fishing or the fishing journal. If you have Enchanting as one of your professions, you will need an enchanted rod to craft most enchants. The exact rod you need will change as you progress but each higher rod will work for all the lower enchants. Also, to make a higher rod usually requires the next lower rod as one of the reagents. Most of the other professions need a tool as well. The tools just has to be in your bags, there is no need to equip them. Some professions require that you do the crafting near something. As you can see from the screenshot I posted, I have the spanner and the hammer but I'm not near an Anvil.

Please take a screenshot at the point when you are confused and post it here. Hopefully, that will help me help you.

**Comment by Addonman** [comment]
[https://imgur.com/KOQ8G3V](url)

Here  is picture of what i was talking about.

**Comment by Addonman** [comment]
Those are slots for profession accesesories and profession tool.

**Comment by b-morgan** [comment]
Thank you for the picture. I forgot to add that Skillet doesn't support the Herbalism Journal, the Fishing Journal, the Skinning Journal, Archeology, or Runeforging. Those gathering professions (and Runeforging) use the standard Blizzard UI.

The buttons you are asking about are on the Blizzard UI and I have no idea what to do with them.

**Comment by Mithmacil** [comment]
This is Gear Slots for Professions so they dont take up inventory space. By the looks of this they might be adding more tools and accessories to help with Crafting/Gathering. 
I have these slots on on all crafting and gathering.
Jewelcrafting tool kit goes in here
![image_2022-11-21_175338004](https://user-images.githubusercontent.com/33404171/203197689-6dc833ba-dfce-4b59-bca6-067aa0f2cf29.png)
