### ISSUE TITLE
Dragonflight Milling does not appear to be implemented 

### ISSUE THREAD

**Issue by grimmtooth** [b-morgan/Skillet#64]
This probably also applies to prospecting, as well.

Image of Inscription interface (native)

![image](https://user-images.githubusercontent.com/16244433/204689728-17d80336-7f5e-43f7-80a4-a6ddd6f1d2a7.png)

So, you select Dragon Isles Milling, and you get a little panel with a little plus on it. Select that panel and you get a menu of available herbs (and unavailable if you so choose)

You then have the option to choose how many grinds of the mill or just select "mill all".

All this is currently missing in the current alpha release (alpha18).

Let me know if you need any files or logs or whatnot.

**Comment by b-morgan** [comment]
This may be the beginning of the end for Skillet. Blizzard has completely revamped professions including the gathering professions which Skillet never really supported. Yes, there was a button in the frame (which has been removed from alpha18) that contained the macro `/cast Milling`) and another one that contained `/cast Prospecting` but that was the extent of Skillet's support for the gathering professions. 

There has never been any documentation on the Blizzard API and it has been a struggle to get Skillet to the point it is at now. At the moment, the only profession that Skillet is really suited for is Cooking which is ironic given the name of the addon.

I only have two characters at level 60 (Mining / Blacksmithing and Tailoring / Engineering). I'm not sure if my character with Inscription or my character with Jewelcrafting can even survive long enough to get to the Dragonflight profession trainers. This will make it difficult to debug any code I add to Skillet.

Skillet has always had the ability to open the Blizzard UI by adding `shift` to the click used to open it. There is also `/skillet standby on` and `/skillet standby off` which can temporarily turn Skillet off with out a `/reload` or a logoff / logon. I'm afraid this is going to be the extent of Skillet's support for the gathering professions and the advanced features of the other professions for now.

**Comment by b-morgan** [comment]
BTW, I was never given a Dragonflight beta key so I've only had two days of exposure to the new gathering interfaces.

**Comment by grimmtooth** [comment]
Yeah, it's a dicey proposition.  If it helps, I was able to get to the inscription trainer on my L60 scribe after doing something like 3 or four quests, and I was able to test by buying 1000 of the basic herb to get a feeling for the process before I wrote anything up.

But honestly, as you say, Skillet's taking a major hit on what is basically an undocumented UI.  You may be right, this may start the beginning of the end for some stuff.

(I'm also annoyed that it looks like there's no ink trader in DF so we're stuck going back to SL herbs for making glyphs. I think they're getting ready to nuke glyphs from orbit. Not that this is your problem to deal with, I just wanted to whine a little :) )

You know, if they just added the ability to buy mats like Skillet does, we might be able to happily retire Skillet, but they don't so we're gonna hate it. :P 

Anyway, holler if you need something.

**Comment by grimmtooth** [comment]
> BTW, I was never given a Dragonflight beta key so I've only had two days of exposure to the new gathering interfaces.

Yeah, it's gonna take a whole to suss this out. I figure it starts with a ticket, and goes from there.

**Comment by b-morgan** [comment]
Wow! I just got on my level 46 Jewelcrafter to see how to prospect old world ore and that's a trip in itself. He is a Death Knight so he might survive on the Dragon Isles long enough to get to the trainers. I'll try after today's maintenance.

**Comment by grimmtooth** [comment]
Good luck!  I mis-read your comment to  think you have a 60 ready to go O.o

**Comment by b-morgan** [comment]
I took the boat to Dragon Isles, attempted to ride to Wingrest Embassy and died. The sprit healer is located just outside of Wingrest Embassy so I took my rez sickness and visited the Jewelcrafting trainer... You have to be level 58 to train...

Good news... I leveled to 47 just by discovering the Dragon Isles!

**Comment by b-morgan** [comment]
Milling and Prospecting are now recipes in Inscription and Jewelcrafting. I have figured out how to identify these recipes (recipeSchematic.recipeType == Enum.TradeskillRecipeType.Salvage) and can get the list of items (itemIDs = C_TradeSkillUI.GetSalvagableItemIDs(recipeID)) that this particular recipe will use.

Classic Milling has 27 items so using the detail side of the Skillet frame isn't going to work. I'll have to invent something similar to what Blizzard uses. I have a template for optional reagents that may work. Then I'll need to determine how to actually "mill" something after it is selected.

My scribe currently has no herbs to mill (he isn't an Herbalist) so I'll have to send my Alchemist / Herbalist out to fetch some (or see if he can afford to buy some in the AH).

**Comment by b-morgan** [comment]
I have attached a pre-alpha version which implements milling (and I hope prospecting) up to the point where you actually execute it (i.e. I'm still trying to figure that part out). I'm making use of code that implements optional reagents so my presentation of the "salvageable" items is different than the Blizzard UI presentation and I'd like your opinion.

[Skillet-5.00-alpha18+.zip](https://github.com/b-morgan/Skillet/files/10143183/Skillet-5.00-alpha18%2B.zip)

**Comment by grimmtooth** [comment]
This looks good, Brad. The only thing I miss from the native version is the ability to filter out items that you don't have any of. That is definitely not a dealbreaker iMO. 

No regressions.

**Comment by b-morgan** [comment]
You miss it and I miss it so I'll add a checkbox to filter out items that you don't have. I did find one issue in that once you select an item to mill, it will show up on any other milling recipe. Its a one line fix. 

I believe I have enough information to actually execute a mill or prospect so I'm working on that code now.

**Comment by grimmtooth** [comment]
Outstanding. Test monkey standing by :)

**Comment by Farelion** [comment]
hey, any chance that you will develop same thing for tailoring cloth unraveling?

**Comment by b-morgan** [comment]
If it uses the same mechanism as milling and prospecting then yes. Download the pre-alpha above and tell us what you see when you select that recipe.

**Comment by Farelion** [comment]
![image](https://user-images.githubusercontent.com/16526340/205453219-d0b510a4-dec7-44f9-95c0-6fa2a8fe48f6.png)
i think it looks kinda the same, i got some screenshots for you, first i choose reagent while unravelling selected, queue all button does nothing, queue button does work and adds recipe below
![image](https://user-images.githubusercontent.com/16526340/205453274-45201294-5c37-4e75-837f-676786469ca3.png)
but pressing any of buttons, create, create all, process gives same output in chat
![image](https://user-images.githubusercontent.com/16526340/205453303-e8c379cf-2537-46a3-873f-9e3ac0e8a548.png)
let my know if i can give any more information

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha19](https://www.curseforge.com/wow/addons/skillet/files/4132186) should work. While you can queue salvage recipes, I have only tested with the "Create" button. The 	C_TradeSkillUI.CraftSalvage function needs to know where the item is in your bags and if your inventory changes (i.e. things move) while a salvage recipe is queued, it will probably fail (spectacularly).

@grimmtooth, I have added a "Hide Unowned" checkbox but it isn't instantaneous. It will close the optional frame and you have to open it again. I'm reusing the code for optional reagents in other professions and many of those optional reagents are craftable so you can add optionals you don't have and Skillet will queue them for crafting.

@Farelion, I released alpha18+ just to see if the UI was acceptable. As you discovered, it didn't actually do something but alpha19 should.

**Comment by Farelion** [comment]
Thanks for answer, ive got the new version, it now kinda works, number in the que box doesnt go down, but it crafts, it only does 200 crafts same as classic ui and then stops with this information 
![image](https://user-images.githubusercontent.com/16526340/205457112-fe673f8d-8125-4c81-8c40-e3bb9c89a375.png)
so i assume its not targeting next stack of cloth correctly, do you think its doable to que more than 200 crafts?

**Comment by b-morgan** [comment]
The adjustment of the number in the queue frame occurs because an event is triggered by Blizzard for each completed iteration. I'll have to see if they added a new event.

Since the C_TradeSkillUI.CraftSalvage function needs to know where the item is in your bags it doesn't surprise me that it doesn't "switch to a new stack" when the first one runs out. I'll look into limiting the actual count to the size of the selected stack and then requeuing the rest. What happens when you try this with the Blizzard UI?

**Comment by Farelion** [comment]
If u ask about how the whole process look in blizz ui then it goes like this:
choose unraveling recipe
click on select reagent (opens box with all clothes that u have in bag split into 1k each)
click on one of stacks ( it says 1000/5 cloth)
click unravel all ( which is 200 cause of 1000/5 )
after that it emptys reagent box and u can choose next stack so u have to click unravell all every 3 minutes which is kinda annoying to do when u unravel like 40k cloth

**Comment by b-morgan** [comment]
That makes sense because of the limitation that it can do at most one stack at a time (other stacks being in other bag locations). I do appreciate your input as it has put stuff on my to do list, i.e. I'll add processing multiple stacks to my list. I'm currently testing with milling herbs gathered from the Elwynn Forest.

My suspicions were correct, Blizzard generates different events for CraftSalvage than it does for CraftRecipe. I'm working on getting the count to decrement and then removing the recipe from the queue when it gets to zero.

**Comment by Farelion** [comment]
Thanks for taking time to look at this problem, im looking forward to processing multiple stack feature if you ever get to implement that

**Comment by b-morgan** [comment]
[Skillet-5.00-alpha20](https://www.curseforge.com/wow/addons/skillet/files/4132622) fixes updating the queue count and removing the command from the queue when complete. The count is adjusted downward if there is insufficient material for the current count. "Create All" or "Queue All" probably won't work yet.

I shuffled some code around so I might have introduced some new bugs. As always, let me know if you find any. I need to go farm more herbs as I'm out and can't test anymore!

**Comment by b-morgan** [comment]
"Create All" and "Queue All" will generate a lua error that can be fixed by changing line 478 in SkilletQueue.lua to:
`count = (skill.numCraftable or 0)/ (recipe.numMade or 1)`
They still don't do anything.

**Comment by b-morgan** [comment]
Attached is a replacement SkilletQueue.lua which should "Queue All" and "Create All" for salvage recipes.

[SkilletQueue.zip](https://github.com/b-morgan/Skillet/files/10148799/SkilletQueue.zip)

> processing multiple stack feature
Unfortunately, this isn't going to happen because Blizzard requires a hardware event (mouse click or key press) per call.

**Comment by Farelion** [comment]
>  Blizzard requires a hardware event (mouse click or key press) per call.
Ah thats so unlucky, thanks for you work mate
