### ISSUE TITLE
Leftover Skill Buttons

### ISSUE THREAD

**Issue by DreamsUnderStars** [b-morgan/Skillet#66]
Extra trade icons on the window when switching professions; from the addons site comments.

[Skillet.zip](https://github.com/b-morgan/Skillet/files/10157236/Skillet.zip)

**Comment by b-morgan** [comment]
Chaandra indeed has data for all of those tradeskills in the database. You have one queued item on Lailanniea and a few options set. These will be reset if you take the simple route which is to type `/skillet flushalldata`. 

There currently isn't an option to just do one character but it can be done manually if you are brave, `Skillet.db.realm.tradeSkills["Chaandra"] = {}` . You could do that for all characters with `/run Skillet.db.realm.tradeSkills = {}`. That data is rebuilt for each character when they first login.

Do any of the above, logout, and login again. If Chaandra still has all of those buttons showing then Blizzard may be lying to Skillet and I'll need to capture more data.

Just out of curiosity, did Chaandra change professions (i.e. did they have the other professions at one time in their life?

**Comment by b-morgan** [comment]
Did clearing the data fix the issue? I've added a `/skillet flushplayerdata` command to the next release. I'll look at determining the current professions in a different way for the future.

**Comment by DreamsUnderStars** [comment]
looks like it fixed it, thanks. :D

**Comment by b-morgan** [comment]
You are welcome!
