### ISSUE TITLE
Not even open/shown?

### ISSUE THREAD

**Issue by Tryko1** [b-morgan/Skillet#68]
<Please include the Skillet version number (from the title or the .toc file)>  4.42 , try with all other AddOns disabled
<Please include the output of "/dump GetLocale()" if it is different than enUS>

21x [string "*MainFrame.xml:1461_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "*MainFrame.xml:1461_OnLoad"]:3: in function <[string "*MainFrame.xml:1461_OnLoad"]:1>

Locals:
(*temporary) = SkilletInventoryFilterOwnedChecked {
 0 = <userdata>
}
(*temporary) = "vertical"
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1

21x [string "*MainFrame.xml:1478_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "*MainFrame.xml:1478_OnLoad"]:3: in function <[string "*MainFrame.xml:1478_OnLoad"]:1>

Locals:
(*temporary) = SkilletInventoryFilterBagChecked {
 0 = <userdata>
}
(*temporary) = "vertical"
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0.500000

21x [string "*MainFrame.xml:1495_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "*MainFrame.xml:1495_OnLoad"]:3: in function <[string "*MainFrame.xml:1495_OnLoad"]:1>

Locals:
(*temporary) = SkilletInventoryFilterCraftChecked {
 0 = <userdata>
}
(*temporary) = "vertical"
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 0.500000

21x [string "*MainFrame.xml:1512_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "*MainFrame.xml:1512_OnLoad"]:3: in function <[string "*MainFrame.xml:1512_OnLoad"]:1>

Locals:
(*temporary) = SkilletInventoryFilterVendorChecked {
 0 = <userdata>
}
(*temporary) = "vertical"
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 0.500000

21x [string "*MainFrame.xml:1529_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "*MainFrame.xml:1529_OnLoad"]:3: in function <[string "*MainFrame.xml:1529_OnLoad"]:1>

Locals:
(*temporary) = SkilletInventoryFilterAltsChecked {
 0 = <userdata>
}
(*temporary) = "vertical"
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1

12x Skillet/Skillet.lua:336: ItemRefTooltip doesn't have a "OnTooltipSetItem" script
[string "=[C]"]: in function `HookScript'
[string "@Skillet/Skillet.lua"]:336: in function <Skillet/Skillet.lua:199>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

20x Skillet/Skillet.lua:783: attempt to index field 'data' (a nil value)
[string "@Skillet/Skillet.lua"]:783: in function `?'
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@DataStore/libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

3x Skillet/UI/MainFrame.xml:866 Unrecognized XML: Backdrop

3x Skillet/UI/MainFrame.xml:866 Unrecognized XML attribute: bgFile

3x Skillet/UI/MainFrame.xml:866 Unrecognized XML attribute: edgeFile

3x Skillet/UI/MainFrame.xml:866 Unrecognized XML attribute: edgeFile

3x Skillet/UI/MainFrame.xml:867 Unrecognized XML: EdgeSize

3x Skillet/UI/MainFrame.xml:868 Unrecognized XML: AbsValue

3x Skillet/UI/MainFrame.xml:868 Unrecognized XML attribute: val

3x Skillet/UI/MainFrame.xml:870 Unrecognized XML: TileSize

3x Skillet/UI/MainFrame.xml:871 Unrecognized XML: AbsValue

3x Skillet/UI/MainFrame.xml:871 Unrecognized XML attribute: val

**Comment by b-morgan** [comment]
As you have discovered, Skillet-4.42 will not work in Dragonflight (10.0.0 or 10.0.2). [Skillet-5.00-beta3](https://www.curseforge.com/wow/addons/skillet/files/4152853) is working but does not have (and may never have) all of the features Blizzard added to Dragonflight professions.
