### ISSUE TITLE
Massive LUA Errors

### ISSUE THREAD

**Issue by Arcaila** [b-morgan/Skillet#70]
Version 4.42

Got about 103 LUA errors for Skillet when logging in. WoW is saying the Addon is out of date. Guessing something in the last update by Blizzard yesterday blew up the code. This is the first error I had. Not sure if you wanted/needed more. All my other addons were turned off so not a conflict. Couldn't even open Skillet. Also, thank you for keeping this up and working on it, even though it sounds like DF has made Addon work a bit tougher for coders.

Message: [string "*MainFrame.xml:1461_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
Time: Wed Dec 14 09:09:06 2022
Count: 1
Stack: [string "*MainFrame.xml:1461_OnLoad"]:3: bad argument #2 to 'SetGradient' (Usage: self:SetGradient(orientation, minColor, maxColor))
[string "=[C]"]: in function `SetGradient'
[string "*MainFrame.xml:1461_OnLoad"]:3: in function <[string "*MainFrame.xml:1461_OnLoad"]:1>

Locals: (*temporary) = SkilletInventoryFilterOwnedChecked {
 0 = <userdata>
}
(*temporary) = "vertical"
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0.500000
(*temporary) = 1

This is the 104th error message once I tried to open my WoW Cooking TS window:

Message: Interface/AddOns/Skillet/UI/MainFrame.lua:176: attempt to call method 'SetGradientAlpha' (a nil value)
Time: Wed Dec 14 09:13:39 2022
Count: 1
Stack: Interface/AddOns/Skillet/UI/MainFrame.lua:176: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Interface/AddOns/Skillet/UI/MainFrame.lua"]:176: in function `CreateTradeSkillWindow'
[string "@Interface/AddOns/Skillet/Skillet.lua"]:1102: in function `SkilletShow'
[string "@Interface/AddOns/Skillet/Skillet.lua"]:883: in function `?'
[string "@Interface/AddOns/Skillet/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...let/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/Skillet/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...let/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/Skillet/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/Skillet/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ce/AddOns/Skillet/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:1175: in function <Interface/FrameXML/ActionButton.lua:1145>
[string "=[C]"]: ?

Locals: <none>

**Comment by b-morgan** [comment]
As you have discovered, Skillet-4.42 will not work in Dragonflight (10.0.0 or 10.0.2). [Skillet-5.00-beta3](https://www.curseforge.com/wow/addons/skillet/files/4152853) is working but does not have (and may never have) all of the features Blizzard added to Dragonflight professions.
