### ISSUE TITLE
Error trying to enchant multiple items

### ISSUE THREAD

**Issue by Fagerinfoco** [b-morgan/Skillet#73]
<Please include the Skillet version number (from the title or the .toc file)>
Version: 5.02
<Please include the output of "/dump GetLocale()" if it is different than enUS>

Attempting to make multiple enchants via the Blizzard UI, as I was unable to create via Skillet. Receive the following error:
Message: Interface/AddOns/Skillet/UI/FinishingList.lua:290: attempt to index local 'thisFinishing' (a nil value)
Time: Tue Jan  3 13:47:49 2023
Count: 1
Stack: Interface/AddOns/Skillet/UI/FinishingList.lua:290: attempt to index local 'thisFinishing' (a nil value)
[string "*MainFrame.xml:802_OnClick"]:13: in function <[string "*MainFrame.xml:802_OnClick"]:1>

Locals: self = SkilletReagent1 {
 0 = <userdata>
}
button = "LeftButton"
down = false
link = "[Chromatic Dust]"

**Comment by b-morgan** [comment]
Do I have this right? You attempted to make multiple enchants with Skillet and it failed with the error or did you attempt to make multiple enchants via the Blizzard UI and you got the error from Skillet?

My Enchanter is level 50 so I haven't been able to do any Enchanting specific debugging. 

Skillet 5.02 doesn't do well with crafting multiples of anything (i.e. any profession) with modified (multiple quality) reagents. Skillet 5.03-alpha2 converts crafting multiples of recipes with modified reagents into a series of single crafts. One of the issues with these recipes is that making 2 or more of something may use a different mix (i.e. different qualities) of the modified reagents for each iteration of the recipe. I've written the code to handle this but I don't believe all of the possible cases have been tested.

Please upload a screenshot of Skillet just before you get the error and show/tell me what you clicked to generate the error.

None of my characters have unlocked an Finishing reagents although the code to handle them is ignoring the locked state for now but I don't know if that is causing your error. I will probably need you to enable the debugging code so I can get some insight into what might be causing the issue.

**Comment by b-morgan** [comment]
[Skillet-5.03-alpha3](https://www.curseforge.com/wow/addons/skillet/files/4296221) will give Enchants from any expansion a fighting chance of working. I still can't test Dragon Isles Enchants directly and I'll probably find more bugs when I try to enchant scrolls but let me know if this gets any closer to working for you.

**Comment by Fagerinfoco** [comment]
Ok, have not moved to the alpha release yet, but here’s some information that may help.

On the skillet screen, when I click create or process (right or left click),the pointer does not have the blue highlighting as previous versions did.

When I switch to the blizzard UI, it does not process multiple but it does allow me to do one at a time. Error appears to be intermittent

**Comment by b-morgan** [comment]
[Skillet-5.03-alpha4](https://www.curseforge.com/wow/addons/skillet/files/4298095)

**Comment by b-morgan** [comment]
This issue was reported against Skillet 5.02 which didn't process Enchants at all. Please open a new issue if problems are encountered in newer versions.
