### ISSUE TITLE
New Feature (Auctionator plugin enhancement)

### ISSUE THREAD

**Issue by Dr0xX3rZ** [b-morgan/Skillet#74]
Hi,

Can you please add the profit line that Auctionator addon add into each under the cost of the item?

thank you

**Comment by b-morgan** [comment]
I don't understand your request. Can you give me more information? A screenshot might help.

If you are talking about information in the recipe detail side of the Skillet frame, then you may have to enable "extra" options in the plugin options for Auctionator.

**Comment by Dr0xX3rZ** [comment]
Hi,

3 screenshots explaining my request.

https://imgur.com/a/MzkjhSX

**Comment by b-morgan** [comment]
Here's what that looks like in the Skillet frame.

![image](https://user-images.githubusercontent.com/1547854/210832322-f2f9a596-b2dd-472c-8376-7bdbba9baa2a.png)

Adding the cost of the modified reagents (in this case, Draconium and Serevite ore) needs to be added to the plugin. Not exactly sure how to handle quality. Should I use the highest, lowest, or some other combination?

**Comment by Dr0xX3rZ** [comment]
Ok, i activated the plugin but yeah the values don't match.

![image](https://user-images.githubusercontent.com/53549192/210835006-5e6fb591-e995-43d4-bb60-647838ebec5e.png)

**Comment by b-morgan** [comment]
I need your help. What would you use for the cost of the modified reagents (the ones with multiple qualities)?

**Comment by Dr0xX3rZ** [comment]
Maybe what is in CraftSim Min Cost Material tab on the right side on my last screenshot. That would be the less expensive material cost to craft the higher level obtainable base on your skill.

**Comment by b-morgan** [comment]
Replace `...\Interface\Addons\Skillet\Plugins\Auctionator.lua` with this one and see if the values aren't closer. I don't believe they will match because I think Auctionator is using the Blizzard UI "To Craft:" value and I have no idea where that comes from.

[Auctionator.zip](https://github.com/b-morgan/Skillet/files/10354304/Auctionator.zip)

**Comment by b-morgan** [comment]
BTW, the Auctionator API I'm using doesn't understand quality, I can only ask for the AH value for the base reagent.

**Comment by Dr0xX3rZ** [comment]
> Replace `...\Interface\Addons\Skillet\Plugins\Auctionator.lua` with this one and see if the values aren't closer. I don't believe they will match because I think Auctionator is using the Blizzard UI "To Craft:" value and I have no idea where that comes from.
> 
> [Auctionator.zip](https://github.com/b-morgan/Skillet/files/10354304/Auctionator.zip)

It is better but still different.

![image](https://user-images.githubusercontent.com/53549192/210854432-e44558c0-40f0-4291-99da-ea7b677bf04f.png)

**Comment by b-morgan** [comment]
The costs are close. The Blizzard UI probably has backdoor access to the AH so its calculations may be real-time and therefore more accurate.

Can you please check the Auctionator plugin options "reagentPrices", "buyablePrices", "useVendorCalc", and "extraBuyout". Also set the "Markup" to 100%.

Please collect a few samples from different recipes. I don't need the screenshots but just the recipe names and the profit differences. I'll install that CraftSim addon and see what that tells me.

If the errors are small, is this is good enough for you to make crafting decisions?

**Comment by Dr0xX3rZ** [comment]
> The costs are close. The Blizzard UI probably has backdoor access to the AH so its calculations may be real-time and therefore more accurate.
> 
> **Can you please check the Auctionator plugin options "reagentPrices", "buyablePrices", "useVendorCalc", and "extraBuyout". Also set the "Markup" to 100%.**
> 
> Please collect a few samples from different recipes. I don't need the screenshots but just the recipe names and the profit differences. I'll install that CraftSim addon and see what that tells me.
> 
> If the errors are small, is this is good enough for you to make crafting decisions?

I don't see anything appearing after adding what you ask me except ATR Buyout which seems fine.

AH cut was not there but I saw after that there is a checkbox for it.

Seems the problem is it's not taking the good rank for buyout

Exemples:
1)WoW UI with Auctionator 2) Skillet
Draconium Needle Set 1) 271g 2) -136g (taking from Buyout R1 instead of R3)
Draconium Leatherworker's Toolset 1) 397g 2)-120g (Taking R1 Buyout instead of R3)
Draconium LEatherworker's Knife 1)535g 2)-128g (Taking R1 Buyout instead of R3)
Draconium Blacksmith's Toolbox 1) 123g 2) -128g (R1 instead of R3)

**Comment by b-morgan** [comment]
I think I screwed up my changes to Auctionator.lua because I'm not seeing the individual costs for buyouts. I'm going to double check my changes.

**Comment by b-morgan** [comment]
Try this one....
[Auctionator.zip](https://github.com/b-morgan/Skillet/files/10355887/Auctionator.zip)

I'm not sure how I get the R1 vs R3 buyout price given the current Auctionator API.

**Comment by Dr0xX3rZ** [comment]
> Try this one.... [Auctionator.zip](https://github.com/b-morgan/Skillet/files/10355887/Auctionator.zip)
> 
> I'm not sure how I get the R1 vs R3 buyout price given the current Auctionator API.

Nah it's still not using the wrong one.

Maybe by item level?

**Comment by b-morgan** [comment]
Its the buyout price that you don't agree with, correct?

I've figured out how to get the prices for the different quality output items but I'm not sure how to use them... for instance:

Draconium Needle Set quality=
4 (the lowest) = 60g
5 = 19000g
6 = 60g
7 = 19000g
8 (the highest) = 688g

Skillet is currently using the quality=4 price for the buyout which I think you are calling R1. Not sure which price is your R3.

Obviously, if I use the maximum or the average instead it is going to be useless on my server because of the bogus 19000g entries.

**Comment by b-morgan** [comment]
This is a quick hack job. There is a new plugin option, "qualityBuyout" that will enable the output of the buyout values of all of the qualities. The formatting is off because the height of the hyperlink isn't the same as the height of the text but I don't expect this code to make it into a release. It will, however, help us figure out what to do next.

[Auctionator.zip](https://github.com/b-morgan/Skillet/files/10356496/Auctionator.zip)

**Comment by Dr0xX3rZ** [comment]
> This is a quick hack job. There is a new plugin option, "qualityBuyout" that will enable the output of the buyout values of all of the qualities. The formatting is off because the height of the hyperlink isn't the same as the height of the text but I don't expect this code to make it into a release. It will, however, help us figure out what to do next.
> 
> [Auctionator.zip](https://github.com/b-morgan/Skillet/files/10356496/Auctionator.zip)
> 
> BTW, these are the quality=4 through quality=8. I don't understand Blizzard's scheme, I just go with it.

I was wrong. Quality is R1 to R5 not R1 to R3. So Blizzard 4 is R1 and 8 is R5. so it should always show you what is the highest you can craft in Buyout.

**Comment by b-morgan** [comment]
(You don't have to quote my responses. The GitHub issue has it all right there.)

So here's the next problem to solve, how do I figure out which is the highest quality you can craft?

I'm not planning on keeping all the rank buyouts so don't get too used to it 😁.

**Comment by Dr0xX3rZ** [comment]
Well, recipe difficulty is how much skill you need to make a R5 (Blizzard 8)

Skill is what you are currently are for the item, rest is irrelevant for now. I'm guessing each item have a table for the 5 ranking of difficulty? (I make it sound easy, I know it's not.)


![image](https://user-images.githubusercontent.com/53549192/210925573-b822327b-297d-4abe-a52b-0b345e92870d.png)

**Comment by b-morgan** [comment]
This is a newer Auctionator.lua than the one in the Skillet.zip file posted in #76. The buyout price is determined by the "Use Best  Quality Reagents" button. When set it uses the price of the quality 8 item and when clear it uses the price of the quality 4 item. This may not be perfect but its a plugin to Skillet and I'm not going to teach it how to determine the best you can do. The only other option I would consider is to use either the min or max of the 5 possible qualities posted.

The qualityBuyout option is still there but will disappear in the next release.

[Auctionator.zip](https://github.com/b-morgan/Skillet/files/10360865/Auctionator.zip)

**Comment by Dr0xX3rZ** [comment]
Would it be possible to simply have a dropbox where you can choose what rank you will be crafting then determining the buyout value?

**Comment by b-morgan** [comment]
A dropbox might work for the detail side of the Skillet frame but on the recipe side the recipeSuffix is filled for each recipe so I'm not sure if a dropdown would work for those.

On the other hand, some good news... I (with help) figured out how to get the messy formatting fixed so the "qualityBuyout" option can stay. Even better, I've added an option "minmaxBuyout" which will output the minimum and the maximum buyout prices of all qualities and use those instead of 4 (R1) and 8 (R5) based on the "Use Best Quality Reagents" button.

There are changes in multiple files so here's a new complete package. [Skillet.zip](https://github.com/b-morgan/Skillet/files/10361979/Skillet.zip)

**Comment by Dr0xX3rZ** [comment]
minmaxbuyout is kind of tricky when this happen:

![image](https://user-images.githubusercontent.com/53549192/211076416-5b24a24c-8a77-456e-82f5-cfeee72b84df.png)

**Comment by b-morgan** [comment]
I hate it when that happens but I don't have control over the Auction House and the trolls that play with it. Skillet is primarily a professions addon. The Auctionator (with Journalator) plugin is a bonus and is not my life's work.

I can make the argument that Auctionator should be given the smarts to filter those "bogus" AH entries so Skillet (via the plugin) never sees them.

I notice that you don't have the Auctionator suffix enabled. That combined with the Auctionator plugin supplied sorts can be quite a powerful tool. I have a user of Skillet-Classic that went from almost nothing to the gold cap on Wrath using the Auctionator + Journalator + DataStore (not yet available on retail) plugins.

The real question is "Is this good enough" for you?

**Comment by Dr0xX3rZ** [comment]
Well best case scenario would be that Buyout is the one that you can actually craft, but yes that good for me. What do you mean by Auctionator suffix enable?

**Comment by b-morgan** [comment]
Unless you can give me (or point me to) a function that returns the quality of the one you can craft, your best case scenario isn't going to happen. Perhaps CraftSim provides such a function. I'd be happy to use another addon's API to get that data.

To set the recipe suffix, see https://github.com/b-morgan/Skillet/issues/74#issuecomment-1372447142 for my settings. You would pick Auctionator in the RecipeNameSuffix dropbox at the top and check one of the "suffix*" options (I use "suffixProfitValue").

This will add the column of values as shown in https://github.com/b-morgan/Skillet/issues/74#issuecomment-1372456359

There are three (four if you count the Journalator one) sorts that you can use to sort your recipes. Note that these temporarily override your suffix* choice which will return when you select a non ATR sort. The sorts may be more meaningful if you change the Grouping to "Flat".

In the next release (coming soon), I've added the DataStoreAuction plugin. When selected in the RecipeNamePrefix dropbox, it will prefix each recipe with the number you have currently posted in the AH (according to the [Altoholic](https://www.curseforge.com/wow/addons/altoholic) addon which provides the DataStore addons).

I've also added the [OribosExchange](https://www.curseforge.com/wow/addons/oribos-exchange) plugin (replacing the obsolete TheUndermineJournal) which will give you another AH datapoint.

**Comment by b-morgan** [comment]
[Skillet-5.03-alpha7](https://www.curseforge.com/wow/addons/skillet/files/4310622) contains this fix.

**Comment by Dr0xX3rZ** [comment]
found this in CraftSim: 

recipeData.expectedQuality = operationInfo.craftingQuality if this can help in something.
