### ISSUE TITLE
First craft not displayed

### ISSUE THREAD

**Issue by Dr0xX3rZ** [b-morgan/Skillet#75]
Skillet 5.02

Hi

The "First Craft" text or icon is not displayed when a first craft is available.

**Comment by b-morgan** [comment]
I'll have to research this one.

**Comment by b-morgan** [comment]
Is this OK?

![image](https://user-images.githubusercontent.com/1547854/210864203-ad750604-f190-4945-96cd-43ad6f615b93.png)

**Comment by b-morgan** [comment]
This will be in the next alpha release. I'm seeing if I can sort out your other issues before I release.

**Comment by b-morgan** [comment]
[Skillet-5.03-alpha7](https://www.curseforge.com/wow/addons/skillet/files/4310622) contains this fix.
