### ISSUE TITLE
Alchemy Transmute

### ISSUE THREAD

**Issue by Dr0xX3rZ** [b-morgan/Skillet#76]
Skillet 5.02

Hi,

In the transmute section 2 different problems:

It is not showing the number out of 7 for transmute available.

It is saying that Cooldown remaining is 48 DAYS

**Comment by b-morgan** [comment]
Can you provide a screenshot that shows the issue, please?

My alchemist is only level 47 and therefore doesn't have the Dragon Isles recipes. If you can demonstrate the issue with Shadowlands or lower recipes, then I'd have a better chance of reproducing it.

Also, Skillet-5.03-alpha5 (or later) has many changes. Not sure they will help in this case but it will be easier for me if we both are using the same code base.

**Comment by Dr0xX3rZ** [comment]
Hi,

Here are 2 screenshots showing in Skillet vs Wow UI. Meanwhile I will switch to alpha version.

https://imgur.com/a/MzkjhSX

**Comment by b-morgan** [comment]
The above imgur link is the same as the one in #74. You can paste images directly into this issue which will help document it.

**Comment by Dr0xX3rZ** [comment]
> The above imgur link is the same as the one in #74. You can paste images directly into this issue which will help document it.

My bad. https://imgur.com/a/FY0rnPM

**Comment by b-morgan** [comment]
I can't find any online documentation for C_TradeSkillUI.GetRecipeCooldown but a search of the BlizzardInterfaceCode reveals 

`local cooldown, isDayCooldown, charges, maxCharges = C_TradeSkillUI.GetRecipeCooldown(skill.id)`

with a much more complicated function to display the cooldown text. I probably need to understand this function and duplicate it but I won't be able to test it so I'll need your help.

**Comment by Dr0xX3rZ** [comment]
> I can't find any online documentation for C_TradeSkillUI.GetRecipeCooldown but a search of the BlizzardInterfaceCode reveals
> 
> `local cooldown, isDayCooldown, charges, maxCharges = C_TradeSkillUI.GetRecipeCooldown(skill.id)`
> 
> with a much more complicated function to display the cooldown text. I probably need to understand this function and duplicate it but I won't be able to test it so I'll need your help.

sure, what can I do?

**Comment by b-morgan** [comment]
I'll write the new function and give you either individual files or a private release. You'll have to see if it works and provide debugging output if it doesn't. I'll include instructions on how to do that if necessary. It may take me a day or two to get this ready.

Alternatively, you can wait until I level my Alchemist to 58 so I can learn Dragon Isles recipes and then however long after that before I learn the transmute that is failing. You will likely to be waiting months 😀.

**Comment by Dr0xX3rZ** [comment]
ready to test when you're done coding!

**Comment by b-morgan** [comment]
Here is a replacement for your current copy of Skillet. The TOC says 5.03-alpha5+ and it is my current working version. It should do something sensible with cooldowns and contains the fixes from all of your other open issues. Please test as many different kinds of cooldowns as you can today and let me know which were successful and if any were unsuccessful. I'd like to publish a new alpha version tomorrow.

[Skillet.zip](https://github.com/b-morgan/Skillet/files/10360527/Skillet.zip)

**Comment by Dr0xX3rZ** [comment]
Seems fine for now. 

![image](https://user-images.githubusercontent.com/53549192/211063762-26b1a43e-cddc-4572-939e-e31e34bf801c.png)
![image](https://user-images.githubusercontent.com/53549192/211065714-3085aba5-12dd-4fd1-bfd4-929180c132cf.png)

**Comment by b-morgan** [comment]
Thank you for checking. The only ones I was able to test were ones that reset daily.

**Comment by b-morgan** [comment]
[Skillet-5.03-alpha7](https://www.curseforge.com/wow/addons/skillet/files/4310622) contains this fix.
