### ISSUE TITLE
Skillet conflicts with addon All the Things

### ISSUE THREAD

**Issue by ishirra** [b-morgan/Skillet#8]
I am using version 4.24 (image says 4.22 but it was taken before I updated the addon)
I have addon All The Things, it gives a window next to the crafting window, to see which recipes I can still get etc.
When Skillet is turned off the window does what it's supposed to do, when Skillet is loaded the window is stuck in the middle of my screen, unmovable and blocking my view and it stops me from being able to click things

![image](https://user-images.githubusercontent.com/4521789/108674485-a33dc800-74e5-11eb-8ec8-2b907cdb55b8.png)

**Comment by b-morgan** [comment]
Skillet doesn't cause this behavior, AllTheThings attaches its window to Blizzard's (invisible, and unmovable) TradeSkillFrame. The following change to AllTheThings.lua starting at line 14901 will get you most of the way there.

```
			elseif SkilletFrame then
				self:SetPoint("TOPLEFT", SkilletFrame, "TOPRIGHT", 0, 0);
				self:SetPoint("BOTTOMLEFT", SkilletFrame, "BOTTOMRIGHT", 0, 0);
				self:SetMovable(true);
			elseif TradeSkillFrame then
				-- Default Alignment on the WoW UI.
				self:SetPoint("TOPLEFT", TradeSkillFrame, "TOPRIGHT", 0, 0);
				self:SetPoint("BOTTOMLEFT", TradeSkillFrame, "BOTTOMRIGHT", 0, 0);
				self:SetMovable(false);
```
