### ISSUE TITLE
Invisible WoW Module

### ISSUE THREAD

**Issue by Callamity** [b-morgan/Skillet#82]
Interface: 100005
Title: Skillet |cff7fff7f -Ace3-|r
my issue, is that for the last 2 days, when i utilize the button for showing the WoW standard Crafting Module, the module shows up invisible. i have reloaded the addon, to no avail. have not added any new addons. and I do NOT get an error on it. it just shows up invisible. except for the tabs lol

**Comment by b-morgan** [comment]
This happens to me as well. I can "fix" the problem in multiple ways. The easiest one is to just click on one of the tabs.

For me, this only happens once per session. Once it has opened correctly one time, it will continue to open correctly until the next login or "/reload".

Other "solutions" include opening the Blizzard UI first, use shift-click on your action bar button. Another is opening a journal that Skillet doesn't support like the Fishing Journal.

**Comment by Callamity** [comment]
Thanks for info!! I appreciate it 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
