### ISSUE TITLE
Well...not a bug, actually

### ISSUE THREAD

**Issue by FlattyOne** [b-morgan/Skillet#83]
Greetings. This is certainly not a bug, but I just don't know what to do) How to change the main Skillet window to the default size? I dragged the lower right corner of the window to resize the Skillet window, but the mouse somehow twitched and this corner went off the screen, completely disappearing. And now I have a skillet window in full screen without the ability to reduce it ((

**Comment by b-morgan** [comment]
Type "/skillet reset" and that should fix you up!

**Comment by FlattyOne** [comment]
Thanks Brad. I typed "/skillet reset", of course, without quotes, but no, it didn't work out, it's still full screen ((I forgot to say, I only have this crap on one character, the rest are fine.

**Comment by b-morgan** [comment]
The Skillet frame(s) need to be created before typing "/skillet reset". Easiest way to do that is to open them. The frame locations and sizes are stored in `World of Warcraft\_retail_\WTF\Account\<name>\<realm>\<character>\layout-local.txt`

**Comment by FlattyOne** [comment]
Very useful information, I will keep it in mind. Thanks again.
