### ISSUE TITLE
Error retrieving mats from Guild Bank

### ISSUE THREAD

**Issue by Fagerinfoco** [b-morgan/Skillet#84]
Version 5.06
When trying to retrieve items from the guild bank,it retrieves a single item then i get this error:

Message: Interface/AddOns/Skillet/UI/ShoppingList.lua:577: attempt to call global 'processGuildQueue' (a nil value)
Time: Sun Feb 12 15:22:52 2023
Count: 1
Stack: Interface/AddOns/Skillet/UI/ShoppingList.lua:577: attempt to call global 'processGuildQueue' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by b-morgan** [comment]
This is fixed in [Skillet-5.07](https://www.curseforge.com/wow/addons/skillet/files/4393871).

**Comment by stmides** [comment]
Version 5.07

Message: Interface/AddOns/Skillet/UI/ShoppingList.lua:1064: attempt to index global 'modifiedInQueue' (a nil value)
Time: Mon Feb 13 11:34:21 2023
Count: 1
Stack: Interface/AddOns/Skillet/UI/ShoppingList.lua:1064: attempt to index global 'modifiedInQueue' (a nil value)
[string "@Interface/AddOns/Skillet/UI/ShoppingList.lua"]:1064: in function `GetReagentsFromBanks'
[string "*ShoppingList.xml:244_OnClick"]:1: in function <[string "*ShoppingList.xml:244_OnClick"]:1>

Locals: self = <table> {
 DeleteIgnoreEntry = <function> defined @Interface/AddOns/Skillet/UI/IgnoreList.lua:170
 VendorItemAvailable = <function> defined @Interface/AddOns/Skillet/Inventory.lua:305
 SkillButton_NewGroup = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:1889
 guildText = 7
 ClearQueue = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:291
 RecipeGroupInitFlatten = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:362
 MERCHANT_UPDATE = <function> defined @Interface/AddOns/Skillet/UI/MerchantWindow.lua:209
 SkilletShow = <function> defined @Interface/AddOns/Skillet/Skillet.lua:1244
 DisplayShoppingList = <function> defined @Interface/AddOns/Skillet/UI/ShoppingList.lua:1316
 ShowQueueView = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:2942
 ReagentStarsFrame_OnMouseEnter = <function> defined @Interface/AddOns/Skillet/UI/DetailFrame.lua:1286
 SKILL_LINES_CHANGED = <function> defined @Interface/AddOns/Skillet/Skillet.lua:913
 SetSelectedTrade = <function> defined @Interface/AddOns/Skillet/Skillet.lua:1575
 FilterDropDown_OnShow = <function> defined @Interface/AddOns/Skillet/UI/Filtering.lua:25
 GARRISON_TRADESKILL_NPC_CLOSED = <function> defined @Interface/AddOns/Skillet/Skillet.lua:1034
 hideTrivialRecipes = false
 SetTradeSkillLearned = <function> defined @Interface/AddOns/Skillet/SkilletData.lua:228
 guildbankQueryComplete = <function> defined @Interface/AddOns/Skillet/UI/ShoppingList.lua:836
 RecipeGroupSort = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:340
 EnableResize = <function> defined @Interface/AddOns/Skillet/UI/Utils.lua:74
 db = <table> {
 }
 bankBusy = false
 UpdateNotesWindow = <function> defined @Interface/AddOns/Skillet/UI/RecipeNotes.lua:116
 SetEnabledState = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 SkilletShowWindow = <function> defined @Interface/AddOns/Skillet/Skillet.lua:1304
 AdditionalButtonsList = <table> {
 }
 CHAT = <function> defined @Interface/AddOns/Skillet/DebugAids.lua:83
 HideOptionalList = <function> defined @Interface/AddOns/Skillet/UI/OptionalList.lua:263
 IgnoreList_OnScroll = <function> defined @Interface/AddOns/Skillet/UI/IgnoreList.lua:288
 SortDropdown_OnLoad = <function> defined @Interface/AddOns/Skillet/UI/Sorting.lua:492
 pluginsOptions = <table> {
 }
 TRADE_SKILL_ITEM_CRAFTED_RESULT = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:825
 NewModule = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 RecipeGroupFlatten = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:378
 RecipeGroupMoveEntry = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:237
 FavoriteButton_OnClick = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:1968
 RegisterProcessQueuePlugin = <function> defined @Interface/AddOns/Skillet/SkilletPlugin.lua:148
 ReagentButtonSkillSelect = <function> defined @Interface/AddOns/Skillet/UI/DetailFrame.lua:1048
 ITEM_DATA_LOAD_RESULT = <function> defined @Interface/AddOns/Skillet/Skillet.lua:1038
 ShowReagentDetails = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:968
 bopCheck = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:1679
 RecipeGroupClearEntries = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:107
 Disable = <function> defined @Interface/AddOns/AdiBags/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 TABLE = <function> defined @Interface/AddOns/Skillet/Debu

**Comment by b-morgan** [comment]
Replace `...\Addons\Skillet\UI\ShoppingList.lua` with the one in this zip file. This should eliminate the lua error. 

There are still cases where Skillet gets confused by items with multiple qualities. This is especially true with Engineering. For example, if you have multiple qualities in the bank, this code fetches the needed quantity of each, i.e. if you need 4 Serevite ore and you have some Q1 and some Q2 ore in the bank, you will get 8 ore in your bags.

[ShoppingList.zip](https://github.com/b-morgan/Skillet/files/10722416/ShoppingList.zip)

Let me know what profession(s) you are using and with what cases does Skillet surprise you with its decisions.

**Comment by b-morgan** [comment]
You can use [Skillet-5.08-alpha1](https://www.curseforge.com/wow/addons/skillet/files/4394518) instead.

**Comment by stmides** [comment]
Will try the alpha build.

On the character that was getting the errors I have Jewlcrafting and
Engineering. The error was on a JC craft.
