### ISSUE TITLE
Problem with "Tailoring Essentials" 

### ISSUE THREAD

**Issue by Pantasaron** [b-morgan/Skillet#85]
Since Version 5.06 I cant choose materials to Unravel or Revraft
In unravelling I see the plus to choose the MAterial, but nothing happens when I click it.
In Recraft I don't have any optio to choose a material.

Disabled all my addons except skillet but the problem still exists.
Changed my language from German to english, but that doesnt help either

**Comment by b-morgan** [comment]
I made a mistake when I implemented optional, modified, finishing, and salvage reagent selection and used left-click to open the selection list. This broke using left-click to select the recipe for a crafted reagent. I moved opening the selection lists to right-click or alt-left-click. I really need a better way to communicate changes like this.

Unravelling (Salvage) is implemented, Recrafting is not (and probably never will be) implemented.

**Comment by Pantasaron** [comment]
Thank you, works perfect
