### ISSUE TITLE
WoWUI showing up invisible with Skillet installed

### ISSUE THREAD

**Issue by gwenskey** [b-morgan/Skillet#86]
Version 5.10
US

My WoW Crafting UI is showing up mostly invisible, I disabled all other addons than Skillet. I reset my SavedVariables, it didn't help.

Having issues with Jewelcrafting, Alchemy, and Engineering. I can occasionally get it to work by waiting or toggling the WOWUI button in Skillet a few times. Has the most issues when not at a Profession crafting table, but still has a lot of issues there as well. Had to reload to get my Crafting Orders to populate as well. 

https://i.imgur.com/h28ip6p.jpeg

**Comment by b-morgan** [comment]
[Skillet-5.11](https://www.curseforge.com/wow/addons/skillet/files/4459260) contains the fix.

**Comment by b-morgan** [comment]
Make that [Skillet-5.13](https://www.curseforge.com/wow/addons/skillet/files/4459294) contains the fix.

**Comment by gwenskey** [comment]
Yaaaaay! Thank you :) :) :)
You fiiiixed it!
