### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by bskoros** [b-morgan/Skillet#88]
<Skillet-5.18)>
Have used Skillet for years, until Dragonflight.  Waited till today to give it another shot and no joy.
As soon as any profession is opened, this pops up...

Message: Interface/AddOns/Skillet/UI/MainFrame.lua:175: attempt to call method 'SetGradientAlpha' (a nil value)
Time: Sun May 28 17:32:24 2023
Count: 6
Stack: Interface/AddOns/Skillet/UI/MainFrame.lua:175: attempt to call method 'SetGradientAlpha' (a nil value)
[string "@Interface/AddOns/Skillet/UI/MainFrame.lua"]:175: in function `CreateTradeSkillWindow'
[string "@Interface/AddOns/Skillet/Skillet.lua"]:932: in function `SkilletShow'
[string "@Interface/AddOns/Skillet/Skillet.lua"]:805: in function `?'
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:1161: in function <Interface/FrameXML/ActionButton.lua:1131>
[string "=[C]"]: ?

Locals: self = <table> {
 DeleteIgnoreEntry = <function> defined @Interface/AddOns/Skillet/UI/IgnoreList.lua:159
 RecipeGroupPruneList = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:487
 SkillButton_NewGroup = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:2056
 modules = <table> {
 }
 CancelTimer = <function> defined @Interface/AddOns/Ace3/AceTimer-3.0/AceTimer-3.0.lua:147
 ClearQueue = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:151
 RecipeGroupAddSubGroup = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:168
 SkillButton_OnDragStop = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:1921
 TradeButtonAdditional_OnEnter = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:579
 RecipeGroupConstructDBString = <function> defined @Interface/AddOns/Skillet/RecipeGroups.lua:463
 QueueAppendCommand = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:49
 tradeSkillOpen = false
 DeleteQueue = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:597
 FormatMoneyShort = <function> defined @Interface/AddOns/Skillet/FormatMoney.lua:180
 DisplayShoppingList = <function> defined @Interface/AddOns/Skillet/UI/ShoppingList.lua:1127
 MerchantBuyButton_OnEnter = <function> defined @Interface/AddOns/Skillet/UI/MerchantWindow.lua:284
 ShowQueueView = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:3258
 QueueAllItems = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:332
 adjustInventory = false
 TRACE_COLOR = ""
 NewModule = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 SKILL_LINES_CHANGED = <function> defined @Interface/AddOns/Skillet/Skillet.lua:756
 SetSelectedTrade = <function> defined @Interface/AddOns/Skillet/Skillet.lua:1276
 CreateStandaloneQueueFrame = <function> defined @Interface/AddOns/Skillet/UI/MainFrame.lua:3308
 FilterDropDown_OnShow = <function> defined @Interface/AddOns/Skillet/UI/Filtering.lua:34
 AddToQueue = <function> defined @Interface/AddOns/Skillet/SkilletQueue.lua:103
 hideTrivialRecipes = false
 dataSourceChanged = false
 SetTradeSkillLearned = <function> defined @Interface/AddOns/Skillet/SkilletData.lua:1136
 guildbankQueryComplete = <function> defined @Interface/AddOns/Skillet/UI/ShoppingList.lua:459
 UpdateMerchantFrame = <function> def

**Comment by b-morgan** [comment]
While you say you are using 5.18, the traceback line numbers do not correspond with the sources for that version. Please download [Skillet-5.18](https://legacy.curseforge.com/wow/addons/skillet/files/4541289), verify the MD5 sum, and install it again.

Let me know if you still have an issue.

**Comment by bskoros** [comment]
You were correct.  I guess I never deleted the old versions (had three separate versions/folders?)  Once I did that and installed the version posted, it works fine.

Thanks for the help!
