### ISSUE TITLE
Skillet.lua:140: attempt to index global 'ProfessionsFrame' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [b-morgan/Skillet#89]
This error pops on first opening.  Also the default trade skill frame opens and not the skillet one.

<Skillet version number (5.22)
<enUS>
2x Skillet/Skillet.lua:140: attempt to index global 'ProfessionsFrame' (a nil value)
[string "@Skillet/Skillet.lua"]:140: in function `DisableBlizzardFrame'
[string "@Skillet/Skillet.lua"]:1297: in function `SkilletShow'
[string "@Skillet/Skillet.lua"]:974: in function `?'
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@DataStore/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `OpenTradeSkill'
[string "@Molinari/hack.lua"]:61: in function <Molinari/hack.lua:54>

Locals:
self = <table> {
 DeleteIgnoreEntry = <function> defined @Skillet/UI/IgnoreList.lua:170
 VendorItemAvailable = <function> defined @Skillet/Inventory.lua:305
 SkillButton_NewGroup = <function> defined @Skillet/UI/MainFrame.lua:1901
 guildText = 0
 ClearQueue = <function> defined @Skillet/SkilletQueue.lua:316
 RecipeGroupInitFlatten = <function> defined @Skillet/RecipeGroups.lua:362
 MERCHANT_UPDATE = <function> defined @Skillet/UI/MerchantWindow.lua:209
 SkilletShow = <function> defined @Skillet/Skillet.lua:1256
 DisplayShoppingList = <function> defined @Skillet/UI/ShoppingList.lua:1320
 ShowQueueView = <function> defined @Skillet/UI/MainFrame.lua:2954
 ReagentStarsFrame_OnMouseEnter = <function> defined @Skillet/UI/DetailFrame.lua:1430
 SKILL_LINES_CHANGED = <function> defined @Skillet/Skillet.lua:925
 SetSelectedTrade = <function> defined @Skillet/Skillet.lua:1587
 FilterDropDown_OnShow = <function> defined @Skillet/UI/Filtering.lua:25
 GARRISON_TRADESKILL_NPC_CLOSED = <function> defined @Skillet/Skillet.lua:1046
 hideTrivialRecipes = false
 SetTradeSkillLearned = <function> defined @Skillet/SkilletData.lua:228
 guildbankQueryComplete = <function> defined @Skillet/UI/ShoppingList.lua:839
 RecipeGroupSort = <function> defined @Skillet/RecipeGroups.lua:340
 EnableResize = <function> defined @Skillet/UI/Utils.lua:74
 db = <table> {
 }
 InitializeSkillLevels = <function> defined @Skillet/SkillLevelData.lua:253
 UpdateNotesWindow = <function> defined @Skillet/UI/RecipeNotes.lua:116
 interface = 100107
 SetEnabledState = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 SkilletShowWindow = <function> defined @Skillet/Skillet.lua:1316
 CHAT = <function> defined @Skillet/DebugAids.lua:83
 HideOptionalList = <function> defined @Skillet/UI/OptionalList.lua:263
 IgnoreList_OnScroll = <function> defined @Skillet/UI/IgnoreList.lua:288
 SortDropdown_OnLoad = <function> defined @Skillet/UI/Sorting.lua:491
 pluginsOptions = <table> {
 }
 TRADE_SKILL_ITEM_CRAFTED_RESULT = <function> defined @Skillet/SkilletQueue.lua:943
 NewModule = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:231
 RecipeGroupFlatten = <function> defined @Skillet/RecipeGroups.lua:378
 FinishChange = <function> defined @Skillet/Skillet.lua:1466
 FavoriteButton_OnClick = <function> defined @Skillet/UI/MainFrame.lua:1980
 RegisterProcessQueuePlugin = <function> defined @Skillet/SkilletPlugin.lua:148
 ReagentButtonSkillSelect = <function> defined @Skillet/UI/DetailFrame.lua:1178
 RequiredListToggleHaveItems = <function> defined @Skillet/UI/RequiredList.lua:24
 ITEM_DATA_LOAD_RESULT = <function> defined @Skillet/Skillet.lua:1050
 ShowReagentDetails = <function> defined @Skillet/UI/MainFrame.lua:972
 bopCheck = <function> defined @Skillet/UI/MainFrame.lua:1691
 RecipeGroupClearEntries = <function> defined @Skillet/RecipeGroups.lua:107
 PrintSaved = <function> defined @Skillet/SkilletQueue.lua:332
 TABLE = <function> defined @Skillet/DebugAids.lua:352
 FixBugs = true
 Unhook = <function> defined @Decursive/Libs/AceHook-3.0/AceHook-3.0.lua:417
 InventoryFilterButton_OnShow = <function> defined @Skillet/UI/MainFrame.lua:2266
 SetTradeSkillToolTip = <function> defined @Skillet/UI/MainFrame.lua:1646
 LEARNED_SPELL_IN_TAB = <function> defined @Skillet/Skillet.lua:934
 ToggleTradeSkillOption = <function> defi

**Comment by b-morgan** [comment]
I cannot reproduce this error. I do notice that the addon Molinari is referenced in the traceback and that addon doesn't appear to be updated for 10.1.7 so I'd like you to disable that addon and see if the problem goes away.

**Comment by b-morgan** [comment]
I installed the addon Molinari (and checked "Load out of date AddOns") and Skillet is still working for me.

Please verify that your install is not corrupt by downloading (and installing) from [https://legacy.curseforge.com/wow/addons/skillet/files](https://legacy.curseforge.com/wow/addons/skillet/files) and verifying the MD5.

You might also uncheck "Load out of date AddOns" to see if some other addon is causing the issue.

If it is still failing, I will need your global saved variables file Skillet.lua and your character specific saved variables file Skillet.lua. You can zip them together if you rename one of them.

**Comment by b-morgan** [comment]
So I tabbed out of WoW to type the above comment and when I returned to WoW, I'm getting this error. I'll get back to you when I figure out what went wrong.

**Comment by b-morgan** [comment]
I tried for an hour on all of my toons with professions and it never happened again so I don't know what to say.

**Comment by Thrumbar** [comment]
Made some changes and stopped my errors..

function Skillet:DisableBlizzardFrame()
    DA.DEBUG(0, "DisableBlizzardFrame()")

    if not ProfessionsFrame then
        DA.DEBUG(0, "ProfessionsFrame is nil!")
        return
    end

    if not self.BlizzardTradeSkillFrame then
        self.BlizzardTradeSkillFrame = ProfessionsFrame
        self.tradeSkillHide = ProfessionsFrame:GetScript("OnHide")
        
         ProfessionsFrame:SetScript("OnHide", nil)

     end

    if self.interface < 100100 then
        SetUIPanelAttribute(ProfessionsFrame, "width", 0) -- Prevent AH from closing when Skillet is opened.
    end

     HideUIPanel(ProfessionsFrame)

    self.BlizzardUIshowing = false
end

Will continue to test and watch..

**Comment by b-morgan** [comment]
I have added similar code to the next release.
