### ISSUE TITLE
Error when queueing items with overlapping prerequisites

### ISSUE THREAD

**Issue by Erstyx** [b-morgan/Skillet#91]
<Please include the Skillet version number (from the title or the .toc file)>
5.2.3
==
Scenario: I'm queueing up a bunch of items so I can make a single trip to the AH before crafting.

Repro steps:
1) Queue an item like Engineering:Tankatronic Goggles. Note that you see 1 Khorium Power Core, 2 Hardened Adamantite Tube, 4 Felsteel Stabilizer and then 1 Tankatronic Goggles in the queue.
2) Queue an item with overlapping prerequisites, like Engineering:Surestrike Goggles V2.0.

Actual behavior: Surestrike Goggles is added to the end of the queue with no other changes.
Expected behavior: As above, but prerequisites are appropriately incremented (2 Khorium Power Core, 4 Hardened Adamantite Tube, 8 Felsteel Stabilizer)

**Comment by b-morgan** [comment]
You can solve this issue by changing line 96 in SkilletQueue.lua from:
`		have = numInBoth + (reagentsInQueue[reagentID] or 0)`
to:
`		have = numInBoth`
I haven't tested other cases (i.e. does this break anything else) so I probably should add an option.

**Comment by b-morgan** [comment]
[Skillet-Classic-1.81-alpha3](https://legacy.curseforge.com/wow/addons/skillet-classic/files) appears to be stable and working in all the cases I could test. There are also a couple of new options, one to control this issue and one to ignore any items in your inventory so the shopping list reflects everything needed. Skillet-Classic 1.81 should be released after the new year.

**Comment by b-morgan** [comment]
Skillet-5.24 contains an option to control this behavior.
