### ISSUE TITLE
Links wrong recipe for enchanting in Classic Era.

### ISSUE THREAD

**Issue by lindenkron** [b-morgan/Skillet#92]
Skillet-Classic 1.80.

It links the enchant that does not work, instead of the recipe.
[Top is Skillet, 2nd one is from wowhead](https://i.imgur.com/6guxBG3.png).

Wowhead one:
https://www.wowhead.com/classic/spell=13937/enchant-2h-weapon-greater-impact

**Comment by lindenkron** [comment]
Nvm, doesn't work in actual chat. Sigh. A feature that would paste the mats individually would be neat then.

**Comment by lindenkron** [comment]
Nvm, doesn't work in actual chat. Sigh. A feature that would paste the mats individually would be neat then.

**Comment by b-morgan** [comment]
Just FYI, this repository is for Skillet (retail), there is a separate one for [Skillet-Classic](https://github.com/b-morgan/Skillet-Classic).

(I thought there was a way to paste the mats... I'll have to remember how) You can link the recipe by right-clicking in the recipe list and select link recipe.
