### ISSUE TITLE
I can't create anyting while trying to lvl blacksmithing in Dragonflight

### ISSUE THREAD

**Issue by ishirra** [b-morgan/Skillet#93]
<Please include the Skillet version number (from the title or the .toc file)>
Skillet 5.24
For some reason, my alt who is a blacksmith (still lvl 1 blacksmithing in Dragonflight blacksmithing) can't create anything. I do have all the mats, the hammer, etc. But the create button is grayed out when being at an anvil. When I disable Skillet, I can create things perfectly fine.  I don't get any LUA-error, or any other error. Nothing happens, I just can't click the button when Skillet is loaded.

**Comment by b-morgan** [comment]
I did find a bug in 5.24 but not the one you are reporting here (i.e. my Create button wasn't grayed out).

Change line 90 in SkilletQueue.lua to be `local have = 0` or wait for 5.25 which I will build in a few minutes.

The only time the Create button is grayed out is when Skillet thinks `if self.currentPlayer ~= (UnitName("player")) then` (line 528 in UI\MainFrame.lua).

Do you have other characters (and/or other professions) on this account that work?

My first guess is either your copy of the addon is corrupt (i.e. please reinstall) or your global saved variables file, Skillet.lua, is corrupt (i.e. please delete it or rename it and try again). 

Let me know if either of these work or not.

**Comment by b-morgan** [comment]
[Skillet-5.25](https://legacy.curseforge.com/wow/addons/skillet/files/4995380) is released.

**Comment by ishirra** [comment]
Skillet worked for all my other chars, just not the Blacksmith one. The button is still grayed out, but I can now click it and create things.  Still not getting an error.

**Comment by b-morgan** [comment]
While on your Blacksmith open Skillet and type the following in chat: `/dump Skillet.currentPlayer`, `/dump UnitName("player")`, and `/dump GetLocale()`. Let me know the results.

In addition, please logout, zip and upload your global saved variables file Skillet.lua and your Blacksmith's saved variables file Skillet.lua. You can put them both in the same zip just rename one of them. 

Lastly, Logon to your Blacksmith and type `/skillet flushplayerdata`. Let me know if that fixes the button.

**Comment by b-morgan** [comment]
I cannot reproduce this error and without additional input, there is nothing I can do.
