### ISSUE TITLE
Does not seem to be able to see reagents in the Warband Bank. 

### ISSUE THREAD

**Issue by jeremy-post** [b-morgan/Skillet#95]
Skillet version 5.30 for Game version 11.0, released July 25, 2024.

Does not seem to be able to see reagents in the Warband Bank.

**Comment by b-morgan** [comment]
Skillet-5.31-alpha1 should see reagents in the Warband Bank (I only have one tab purchased ATM). 

You will have to help me figure out what else doesn't work (i.e. seeing and using might need different changes).

**Comment by jeremy-post** [comment]
I just updated to 5.31-alpha1 and I wanted to confirm that I can see and use Warband Bank reagents with that version. I've only tested some transmutes, but it seems to be working correctly with this version. Thanks for your quick response.
