### ISSUE TITLE
Mats not fitting the Shopping list Window after expanding it past the Mats

### ISSUE THREAD

**Issue by alexdk** [b-morgan/Skillet#98]
Version: 5.32
enUS

After expanding the shopping list past the different mats for the queued up recipes, it can no longer hide those mats again if i make the window smaller, and closing the window and opening it again does not change anything

![Udklip](https://github.com/user-attachments/assets/6f0f3d2a-334f-4659-9a33-1a059d800426)

**Comment by b-morgan** [comment]
This should be fixed in [Skillet-5.33-alpha3](https://legacy.curseforge.com/wow/addons/skillet/files/5722684).

**Comment by alexdk** [comment]
Just updated to the newest version and the issue has been fixed
